sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - libc6-dev-i386
      - libmysqlclient-dev
      - libsqlite3-dev
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-test-dev
before_script:
  - wget http://root.cern.ch/download/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz
  - tar -xzf root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz
  - source root/bin/thisroot.sh
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - ./asym -h # dummy run all executables
  - ./malpha -h # for example checks for dynamic libraries loading
  - ./masym -h
#  - ./spinflipper
