cnipol: src/AsymPlot.cxx File Reference
AsymPlot.cxx File Reference
#include "AsymPlot.h"
#include <getopt.h>
Functions
Int_t FileNotOK (Char_t file[])
18 Oct, 2010 - Dmitri Smirnov
Int_t Usage (char *argv[])
Int_t Example (char *argv[])
void ColorSkime ()
Int_t IsOK (const Char_t histname[])
int main (int argc, char **argv)
Function Documentation
void ColorSkime ()
Definition at line 61 of file AsymPlot.cxx.
Int_t Example (char * argv[])
Definition at line 51 of file AsymPlot.cxx.
Int_t FileNotOK (Char_t file[])
18 Oct, 2010 - Dmitri Smirnov
Reorganized the file structure. Moved all definitions into the header file
Definition at line 23 of file AsymPlot.cxx.
Referenced by AsymPlot::FindRootFile().
Int_t IsOK (const Char_t histname[])
Definition at line 79 of file AsymPlot.cxx.
Referenced by AsymPlot::PlotBanana(), AsymPlot::PlotFeedbackStrip(), AsymPlot::PlotInvariantMass(), AsymPlot::PlotMassEnergyCorrelation(), and AsymPlot::PlotStrip().
int main (int argc, char ** argv)
Definition at line 426 of file AsymPlot.cxx.
Int_t Usage (char * argv[])
Definition at line 30 of file AsymPlot.cxx.
Referenced by main().