cnipol: AnaFillResult Class Reference
AnaFillResult Class Reference
#include <AnaFillResult.h>
Public Member Functions
AnaFillResult (UInt_t fillId=0)
~AnaFillResult ()
time_t GetStartTime () const
time_t GetEndTime () const
time_t GetLumiOnRelTime () const
time_t GetLumiOffRelTime () const
time_t GetLumiOnTime () const
time_t GetLumiOffTime () const
void Print (const Option_t *opt="") const
AnaGlobResult * GetAnaGlobResult () const
void SetAnaGlobResult (AnaGlobResult *agr)
UInt_t GetFillId () const
Double_t GetFlattopEnergy () const
EFillType GetFillType () const
TGraphErrors * GetGrBluIntens () const
TGraphErrors * GetGrYelIntens () const
TGraphErrors * GetIntensGraph (ERingId ringId) const
ValErrPair GetIntensDecay (ERingId ringId) const
TGraphErrors * GetRotCurStarGraph (ERingId ringId) const
TGraphErrors * GetRotCurPhenixGraph (ERingId ringId) const
TGraphErrors * GetSnakeCurGraph (ERingId ringId) const
std::vector< TGraphErrors * > GetBCCurGraphs (EPolarimeterId polId) const
void AddMeasResult (AnaMeasResult &result)
void AddMeasResult (EventConfig &mm)
void AddGraphMeasResult (EventConfig &mm, DrawObjContainer &ocIn)
This func can be (should be?) merged with AddMeasResult.
void Process (DrawObjContainer *ocOut=0)
Bool_t IsValidFlattopMeas (const MeasInfo &measInfo)
ValErrPair GetPCPolar (EPolarimeterId polId, PolId2ValErrMap *normJC=0) const
ValErrPair GetPCPolarUnW (EPolarimeterId polId, PolId2ValErrMap *normJC=0) const
TGraphErrors * GetPCPolarGraph (EPolarimeterId polId) const
Function can return an empty graph.
TGraphErrors * GetPCPolarInjGraph (EPolarimeterId polId)
Function cannot return empty graph.
ValErrPair GetPCPolarP0 (EPolarimeterId polId) const
ValErrPair GetPCPolarSlope (EPolarimeterId polId) const
TargetUId GetPCTarget (EPolarimeterId polId) const
ValErrPair GetHJPolar (EPolarimeterId polId)
ValErrPair GetHJPolar (ERingId ringId) const
ValErrPair GetHJAsym (EPolarimeterId polId)
ValErrPair GetHJAsym (ERingId ringId)
ValErrPair GetBeamPolar (ERingId ringId) const
ValErrPair GetBeamPolarP0 (ERingId ringId) const
ValErrPair GetBeamPolarDecay (ERingId ringId) const
ValErrPair GetPolarUDRatio (ERingId ringId)
ValErrPair GetSystJvsCPolar (EPolarimeterId polId)
ValErrPair GetSystProfPolar (EPolarimeterId polId)
TGraphErrors * GetPCProfRGraph (EPolarimeterId polId, ETargetOrient tgtOrient) const
Function can return an empty graph.
TGraphErrors * GetPCProfRInjGraph (EPolarimeterId polId, ETargetOrient tgtOrient) const
Function can return an empty graph.
ValErrPair GetPCProfR (ERingId ringId, ETargetOrient tgtOrient) const
ValErrPair GetPCProfR (EPolarimeterId polId, ETargetOrient tgtOrient) const
ValErrPair GetPCProfRInj (EPolarimeterId polId, ETargetOrient tgtOrient) const
ValErrPair GetPCProfR0 (EPolarimeterId polId, ETargetOrient tgtOrient) const
ValErrPair GetPCProfRSlope (EPolarimeterId polId, ETargetOrient tgtOrient) const
ValErrPair GetPCProfPMax (ERingId ringId, ETargetOrient tgtOrient) const
ValErrPair GetPCProfP (ERingId ringId, ETargetOrient tgtOrient) const
void CalcBeamPolar (Bool_t doNorm=kFALSE)
RingId2ValErrMap CalcPolarRatioU2D (PolId2ValErrMap &normJC)
PolId2ValErrMap CalcSystJvsCPolar (PolId2ValErrMap &normJC)
Calculates and returns the ratio of the HJ to PC polarization.
PolId2ValErrMap CalcSystProfPolar (PolId2ValErrMap &normPP)
ValErrPair CalcAvrgPolar (EPolarimeterId polId)
ValErrPair CalcAvrgPolarUnweighted (EPolarimeterId polId)
ValErrPair CalcAvrgPolProfPolar (EPolarimeterId polId)
ValErrPair CalcAvrgProfR (EPolarimeterId polid, ETargetOrient tgtOrient)
ValErrPair CalcAvrgPolProfR (ERingId ringId, ETargetOrient tgtOrient)
ValErrPair CalcAvrgPolProfPMax (ERingId ringId, ETargetOrient tgtOrient)
ValErrPair CalcPolProfP (ValErrPair R, ValErrPair PMax)
void CalcRotatorPCPolarRatio ()
void CalcRampPCPolarRatio ()
void CalcAvrgAsymByBunch (const AnaMeasResult &amr, const MeasInfo &mi, DrawObjContainer &ocOut) const
void UpdateExternGraphRange ()
void FitExternGraphs ()
void FitPCPolarGraphs ()
void FitPCProfRGraphs ()
void SetHJPolar (ERingId ringId, ValErrPair ve)
void SetHJAsym (ERingId ringId, ValErrPair ve)
void AppendToPCPolarGraph (EPolarimeterId polId, Double_t x, Double_t y, Double_t xe, Double_t ye)
void AppendToPCPolarInjGraph (EPolarimeterId polId, Double_t x, Double_t y, Double_t xe, Double_t ye)
void AppendToPCProfRGraph (EPolarimeterId polId, ETargetOrient tgtOrient, Double_t x, Double_t y, Double_t xe, Double_t ye)
void AppendToPCProfRInjGraph (EPolarimeterId polId, ETargetOrient tgtOrient, Double_t x, Double_t y, Double_t xe, Double_t ye)
Public Attributes
AnaMeasResultMap fAnaMeasResults
MeasInfoMap fMeasInfos
PolId2MeasInfoPtrSetMap fMeasInfosByPolId
PolId2ValErrMap fPCPolars
PolId2ValErrMap fPCPolarUnWs
PolId2TgtOrient2ValErrMap fPCProfRs
TargetUId2ValErrMap fPCPolarsByTargets
PolId2ValErrMap fPCProfPolars
RingId2ValErrMap fHJPolars
RingId2ValErrMap fHJAsyms
RingId2ValErrMap fBeamPolars
RingId2ValErrMap fBeamPolarP0s
RingId2ValErrMap fBeamPolarSlopes
RingId2ValErrMap fBeamCollPolars
PolId2ValErrMap fSystProfPolar
not used
PolId2ValErrMap fSystJvsCPolar
RingId2ValErrMap fPolarRatioU2D
PolId2ValErrMap fRotatorPCPolarRatio
PolId2ValErrMap fRampPCPolarRatio
String2TgtOrientMap fMeasTgtOrients
before/after ramp to flattop ratio
String2TargetIdMap fMeasTgtIds
String2RingIdMap fMeasRingIds
RingId2TgtOrient2ValErrMap fPolProfRs
RingId2TgtOrient2ValErrMap fPolProfPMaxs
RingId2TgtOrient2ValErrMap fPolProfPs
Protected Attributes
UInt_t fFillId
AnaGlobResult * fAnaGlobResult
time_t fStartTime
time_t fEndTime
AnaFillExternResult fAnaFillExternResult
PolId2TGraphMap fPCPolarGraphs
PolId2TGraphMap fPCPolarInjGraphs
PolId2TgtOrient2TGraphMap fPCProfRGraphs
PolId2TgtOrient2TGraphMap fPCProfRInjGraphs
PolId2TargetUIdMap fPCTargets
TFitResultPtr fPCPolarFitRes
TFitResultPtr fPolProfRFitRes
Double_t fFlattopEnergy
EFillType fFillType
Detailed Description
Definition at line 28 of file AnaFillResult.h.
Constructor & Destructor Documentation
AnaFillResult::AnaFillResult (UInt_t fillId = 0)
Definition at line 24 of file AnaFillResult.cxx.
AnaFillResult::~AnaFillResult ()
Definition at line 65 of file AnaFillResult.cxx.
Member Function Documentation
void AnaFillResult::AddGraphMeasResult (EventConfig & mm, DrawObjContainer & ocIn)
This func can be (should be?) merged with AddMeasResult.
Definition at line 287 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::AddMeasResult().
void AnaFillResult::AddMeasResult (AnaMeasResult & result)
Definition at line 253 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::AddMeasResult().
void AnaFillResult::AddMeasResult (EventConfig & mm)
Definition at line 259 of file AnaFillResult.cxx.
void AnaFillResult::AppendToPCPolarGraph (EPolarimeterId polId, Double_t x, Double_t y, Double_t xe, Double_t ye)
Definition at line 1590 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::AppendToPCPolarInjGraph (EPolarimeterId polId, Double_t x, Double_t y, Double_t xe, Double_t ye)
Definition at line 1606 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::AppendToPCProfRGraph (EPolarimeterId polId, ETargetOrient tgtOrient, Double_t x, Double_t y, Double_t xe, Double_t ye)
Definition at line 1621 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::AppendToPCProfRInjGraph (EPolarimeterId polId, ETargetOrient tgtOrient, Double_t x, Double_t y, Double_t xe, Double_t ye)
Definition at line 1637 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::CalcAvrgAsymByBunch (const AnaMeasResult & amr, const MeasInfo & mi, DrawObjContainer & ocOut) const
Definition at line 1266 of file AnaFillResult.cxx.
Referenced by Process().
ValErrPair AnaFillResult::CalcAvrgPolar (EPolarimeterId polId)
Definition at line 934 of file AnaFillResult.cxx.
Referenced by Process().
ValErrPair AnaFillResult::CalcAvrgPolarUnweighted (EPolarimeterId polId)
Definition at line 993 of file AnaFillResult.cxx.
Referenced by CalcAvrgPolar(), and Process().
ValErrPair AnaFillResult::CalcAvrgPolProfPMax (ERingId ringId, ETargetOrient tgtOrient)
Definition at line 1136 of file AnaFillResult.cxx.
Referenced by Process().
ValErrPair AnaFillResult::CalcAvrgPolProfPolar (EPolarimeterId polId)
Definition at line 1030 of file AnaFillResult.cxx.
Referenced by Process().
ValErrPair AnaFillResult::CalcAvrgPolProfR (ERingId ringId, ETargetOrient tgtOrient)
Definition at line 1102 of file AnaFillResult.cxx.
Referenced by Process().
ValErrPair AnaFillResult::CalcAvrgProfR (EPolarimeterId polid, ETargetOrient tgtOrient)
Definition at line 1065 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::CalcBeamPolar (Bool_t doNorm = kFALSE)
Definition at line 713 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::CalcDependencies().
RingId2ValErrMap AnaFillResult::CalcPolarRatioU2D (PolId2ValErrMap & normJC)
Definition at line 748 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::CalcDependencies().
ValErrPair AnaFillResult::CalcPolProfP (ValErrPair R, ValErrPair PMax)
Definition at line 1173 of file AnaFillResult.cxx.
Referenced by CalcAvrgPolProfPolar(), and Process().
void AnaFillResult::CalcRampPCPolarRatio ()
Definition at line 1237 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::CalcRotatorPCPolarRatio ()
Definition at line 1192 of file AnaFillResult.cxx.
Referenced by Process().
PolId2ValErrMap AnaFillResult::CalcSystJvsCPolar (PolId2ValErrMap & normJC)
Calculates and returns the ratio of the HJ to PC polarization.
The latter is expected to be normalized.
Definition at line 787 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::CalcDependencies().
PolId2ValErrMap AnaFillResult::CalcSystProfPolar (PolId2ValErrMap & normPP)
Definition at line 815 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::CalcDependencies().
void AnaFillResult::FitExternGraphs ()
Definition at line 1365 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::FitPCPolarGraphs ()
Definition at line 1406 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::FitPCProfRGraphs ()
Definition at line 1497 of file AnaFillResult.cxx.
Referenced by Process().
AnaGlobResult* AnaFillResult::GetAnaGlobResult () const inline
Definition at line 98 of file AnaFillResult.h.
std::vector< TGraphErrors * > AnaFillResult::GetBCCurGraphs (EPolarimeterId polId) const
Definition at line 243 of file AnaFillResult.cxx.
Referenced by MAsymSingleFillHists::PostFill(), and UpdateExternGraphRange().
ValErrPair AnaFillResult::GetBeamPolar (ERingId ringId) const
Definition at line 668 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::GetBeamPolar().
ValErrPair AnaFillResult::GetBeamPolarDecay (ERingId ringId) const
Definition at line 684 of file AnaFillResult.cxx.
Referenced by SetValues().
ValErrPair AnaFillResult::GetBeamPolarP0 (ERingId ringId) const
Definition at line 676 of file AnaFillResult.cxx.
Referenced by SetValues().
time_t AnaFillResult::GetEndTime () const
Definition at line 70 of file AnaFillResult.cxx.
Referenced by MAsymSingleFillHists::BookHists().
UInt_t AnaFillResult::GetFillId () const inline
Definition at line 100 of file AnaFillResult.h.
Referenced by MAsymFillHists::GetSingleFillHists(), SetValues(), and AnaGlobResult::UpdateInsertDb().
EFillType AnaFillResult::GetFillType () const inline
Definition at line 102 of file AnaFillResult.h.
Referenced by SetValues().
Double_t AnaFillResult::GetFlattopEnergy () const inline
Definition at line 101 of file AnaFillResult.h.
Referenced by SetValues().
TGraphErrors * AnaFillResult::GetGrBluIntens () const
Definition at line 166 of file AnaFillResult.cxx.
Referenced by GetIntensGraph().
TGraphErrors * AnaFillResult::GetGrYelIntens () const
Definition at line 167 of file AnaFillResult.cxx.
Referenced by GetIntensGraph().
ValErrPair AnaFillResult::GetHJAsym (EPolarimeterId polId)
Definition at line 653 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetHJAsym (ERingId ringId)
Definition at line 661 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetHJPolar (EPolarimeterId polId)
Definition at line 638 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::CalcPolarNorm(), CalcSystJvsCPolar(), SetValues(), and SetValuesHJ().
ValErrPair AnaFillResult::GetHJPolar (ERingId ringId) const
Definition at line 646 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetIntensDecay (ERingId ringId) const
Definition at line 183 of file AnaFillResult.cxx.
TGraphErrors * AnaFillResult::GetIntensGraph (ERingId ringId) const
Definition at line 171 of file AnaFillResult.cxx.
Referenced by CalcAvrgPolar(), FitExternGraphs(), GetIntensDecay(), MAsymSingleFillHists::PostFill(), and UpdateExternGraphRange().
time_t AnaFillResult::GetLumiOffRelTime () const
Definition at line 72 of file AnaFillResult.cxx.
Referenced by CalcAvrgPolarUnweighted(), CalcAvrgProfR(), FitPCPolarGraphs(), and FitPCProfRGraphs().
time_t AnaFillResult::GetLumiOffTime () const
Definition at line 74 of file AnaFillResult.cxx.
time_t AnaFillResult::GetLumiOnRelTime () const
Definition at line 71 of file AnaFillResult.cxx.
Referenced by CalcAvrgPolar(), CalcAvrgPolarUnweighted(), CalcAvrgProfR(), FitPCPolarGraphs(), and FitPCProfRGraphs().
time_t AnaFillResult::GetLumiOnTime () const
Definition at line 73 of file AnaFillResult.cxx.
Referenced by FitPCPolarGraphs(), and FitPCProfRGraphs().
ValErrPair AnaFillResult::GetPCPolar (EPolarimeterId polId, PolId2ValErrMap * normJC = 0) const
Definition at line 453 of file AnaFillResult.cxx.
Referenced by CalcBeamPolar(), CalcPolarRatioU2D(), CalcSystJvsCPolar(), MAsymSingleFillHists::PostFill(), Print(), SetValues(), and SetValuesPC().
TGraphErrors * AnaFillResult::GetPCPolarGraph (EPolarimeterId polId) const
Function can return an empty graph.
Definition at line 498 of file AnaFillResult.cxx.
Referenced by AppendToPCPolarGraph(), CalcAvrgPolar(), CalcAvrgPolarUnweighted(), CalcRampPCPolarRatio(), FitPCPolarGraphs(), GetPCPolarP0(), GetPCPolarSlope(), and MAsymSingleFillHists::PostFill().
TGraphErrors * AnaFillResult::GetPCPolarInjGraph (EPolarimeterId polId)
Function cannot return empty graph.
Definition at line 509 of file AnaFillResult.cxx.
Referenced by AppendToPCPolarInjGraph(), CalcRampPCPolarRatio(), FitPCPolarGraphs(), and MAsymSingleFillHists::PostFill().
ValErrPair AnaFillResult::GetPCPolarP0 (EPolarimeterId polId) const
Definition at line 566 of file AnaFillResult.cxx.
Referenced by CalcBeamPolar(), CalcRampPCPolarRatio(), and SetValuesPC().
ValErrPair AnaFillResult::GetPCPolarSlope (EPolarimeterId polId) const
Definition at line 584 of file AnaFillResult.cxx.
Referenced by CalcBeamPolar(), and SetValuesPC().
ValErrPair AnaFillResult::GetPCPolarUnW (EPolarimeterId polId, PolId2ValErrMap * normJC = 0) const
Definition at line 476 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetPCProfP (ERingId ringId, ETargetOrient tgtOrient) const
Definition at line 917 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetPCProfPMax (ERingId ringId, ETargetOrient tgtOrient) const
Definition at line 900 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetPCProfR (ERingId ringId, ETargetOrient tgtOrient) const
Definition at line 848 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::CalcAvrgPolProfR(), SetValues(), and AnaGlobResult::UpdateInsertDb().
ValErrPair AnaFillResult::GetPCProfR (EPolarimeterId polId, ETargetOrient tgtOrient) const
Definition at line 865 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetPCProfR0 (EPolarimeterId polId, ETargetOrient tgtOrient) const
Definition at line 602 of file AnaFillResult.cxx.
Referenced by SetValues().
TGraphErrors * AnaFillResult::GetPCProfRGraph (EPolarimeterId polId, ETargetOrient tgtOrient) const
Function can return an empty graph.
Definition at line 520 of file AnaFillResult.cxx.
Referenced by AppendToPCProfRGraph(), CalcAvrgProfR(), FitPCProfRGraphs(), GetPCProfR0(), GetPCProfRSlope(), and MAsymSingleFillHists::PostFill().
ValErrPair AnaFillResult::GetPCProfRInj (EPolarimeterId polId, ETargetOrient tgtOrient) const
Definition at line 882 of file AnaFillResult.cxx.
TGraphErrors * AnaFillResult::GetPCProfRInjGraph (EPolarimeterId polId, ETargetOrient tgtOrient) const
Function can return an empty graph.
Definition at line 543 of file AnaFillResult.cxx.
Referenced by AppendToPCProfRInjGraph(), FitPCProfRGraphs(), and GetPCProfRInj().
ValErrPair AnaFillResult::GetPCProfRSlope (EPolarimeterId polId, ETargetOrient tgtOrient) const
Definition at line 620 of file AnaFillResult.cxx.
Referenced by SetValues().
TargetUId AnaFillResult::GetPCTarget (EPolarimeterId polId) const inline
Definition at line 122 of file AnaFillResult.h.
Referenced by AnaGlobResult::CalcPolarNorm(), Print(), and SetValues().
ValErrPair AnaFillResult::GetPolarUDRatio (ERingId ringId)
Definition at line 692 of file AnaFillResult.cxx.
TGraphErrors * AnaFillResult::GetRotCurPhenixGraph (ERingId ringId) const
Definition at line 216 of file AnaFillResult.cxx.
Referenced by MAsymSingleFillHists::PostFill(), and UpdateExternGraphRange().
TGraphErrors * AnaFillResult::GetRotCurStarGraph (ERingId ringId) const
Definition at line 202 of file AnaFillResult.cxx.
Referenced by MAsymSingleFillHists::PostFill(), and UpdateExternGraphRange().
TGraphErrors * AnaFillResult::GetSnakeCurGraph (ERingId ringId) const
Definition at line 230 of file AnaFillResult.cxx.
Referenced by MAsymSingleFillHists::PostFill(), and UpdateExternGraphRange().
time_t AnaFillResult::GetStartTime () const
Definition at line 69 of file AnaFillResult.cxx.
Referenced by MAsymSingleFillHists::BookHists(), FitPCPolarGraphs(), FitPCProfRGraphs(), MAsymSingleFillHists::PostFill(), Process(), and SetValues().
ValErrPair AnaFillResult::GetSystJvsCPolar (EPolarimeterId polId)
Definition at line 699 of file AnaFillResult.cxx.
ValErrPair AnaFillResult::GetSystProfPolar (EPolarimeterId polId)
Definition at line 706 of file AnaFillResult.cxx.
Bool_t AnaFillResult::IsValidFlattopMeas (const MeasInfo & measInfo)
Definition at line 444 of file AnaFillResult.cxx.
Referenced by Process().
void AnaFillResult::Print (const Option_t * opt = "") const
Definition at line 78 of file AnaFillResult.cxx.
void AnaFillResult::Process (DrawObjContainer * ocOut = 0)
Definition at line 315 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::Process().
void AnaFillResult::SetAnaGlobResult (AnaGlobResult * agr) inline
Definition at line 99 of file AnaFillResult.h.
Referenced by AnaGlobResult::GetAnaFillResult().
void AnaFillResult::SetHJAsym (ERingId ringId, ValErrPair ve)
Definition at line 1583 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::AddHJMeasResult().
void AnaFillResult::SetHJPolar (ERingId ringId, ValErrPair ve)
Definition at line 1576 of file AnaFillResult.cxx.
Referenced by AnaGlobResult::AddHJMeasResult().
void AnaFillResult::UpdateExternGraphRange ()
Definition at line 1315 of file AnaFillResult.cxx.
Referenced by Process().
Member Data Documentation
AnaFillExternResult AnaFillResult::fAnaFillExternResult protected
Definition at line 36 of file AnaFillResult.h.
Referenced by FitExternGraphs(), GetBCCurGraphs(), GetGrBluIntens(), GetGrYelIntens(), GetLumiOffRelTime(), GetLumiOffTime(), GetLumiOnRelTime(), GetLumiOnTime(), GetRotCurPhenixGraph(), GetRotCurStarGraph(), GetSnakeCurGraph(), and Process().
AnaGlobResult* AnaFillResult::fAnaGlobResult protected
Definition at line 33 of file AnaFillResult.h.
Referenced by CalcBeamPolar(), GetAnaGlobResult(), and Print().
AnaMeasResultMap AnaFillResult::fAnaMeasResults
Definition at line 52 of file AnaFillResult.h.
Referenced by AddGraphMeasResult(), AddMeasResult(), CalcAvrgPolProfPMax(), CalcAvrgPolProfPolar(), CalcAvrgPolProfR(), CalcRotatorPCPolarRatio(), Print(), and Process().
RingId2ValErrMap AnaFillResult::fBeamCollPolars
Definition at line 67 of file AnaFillResult.h.
RingId2ValErrMap AnaFillResult::fBeamPolarP0s
Definition at line 65 of file AnaFillResult.h.
Referenced by CalcBeamPolar(), and GetBeamPolarP0().
RingId2ValErrMap AnaFillResult::fBeamPolars
Definition at line 64 of file AnaFillResult.h.
Referenced by CalcBeamPolar(), CalcPolarRatioU2D(), and GetBeamPolar().
RingId2ValErrMap AnaFillResult::fBeamPolarSlopes
Definition at line 66 of file AnaFillResult.h.
Referenced by CalcBeamPolar(), and GetBeamPolarDecay().
time_t AnaFillResult::fEndTime protected
Definition at line 35 of file AnaFillResult.h.
Referenced by AddMeasResult(), and GetEndTime().
UInt_t AnaFillResult::fFillId protected
Definition at line 32 of file AnaFillResult.h.
Referenced by AppendToPCPolarGraph(), AppendToPCPolarInjGraph(), AppendToPCProfRGraph(), AppendToPCProfRInjGraph(), CalcAvrgAsymByBunch(), CalcAvrgPolar(), CalcBeamPolar(), FitPCPolarGraphs(), FitPCProfRGraphs(), GetFillId(), GetIntensDecay(), and Print().
EFillType AnaFillResult::fFillType protected
Definition at line 48 of file AnaFillResult.h.
Referenced by GetFillType(), and Process().
Double_t AnaFillResult::fFlattopEnergy protected
Definition at line 47 of file AnaFillResult.h.
Referenced by GetFlattopEnergy(), and Process().
RingId2ValErrMap AnaFillResult::fHJAsyms
Definition at line 62 of file AnaFillResult.h.
Referenced by GetHJAsym(), and SetHJAsym().
RingId2ValErrMap AnaFillResult::fHJPolars
Definition at line 61 of file AnaFillResult.h.
Referenced by GetHJPolar(), SetHJPolar(), and SetValues().
MeasInfoMap AnaFillResult::fMeasInfos
Definition at line 53 of file AnaFillResult.h.
Referenced by AddMeasResult(), and Process().
PolId2MeasInfoPtrSetMap AnaFillResult::fMeasInfosByPolId
Definition at line 54 of file AnaFillResult.h.
Referenced by AddMeasResult(), CalcRotatorPCPolarRatio(), and MAsymSingleFillHists::PostFill().
String2RingIdMap AnaFillResult::fMeasRingIds
Definition at line 78 of file AnaFillResult.h.
Referenced by AddMeasResult(), CalcAvrgPolProfPMax(), and CalcAvrgPolProfR().
String2TargetIdMap AnaFillResult::fMeasTgtIds
Definition at line 77 of file AnaFillResult.h.
Referenced by AddMeasResult(), and Process().
String2TgtOrientMap AnaFillResult::fMeasTgtOrients
before/after ramp to flattop ratio
Definition at line 76 of file AnaFillResult.h.
Referenced by AddMeasResult(), CalcAvrgPolProfPMax(), CalcAvrgPolProfR(), and Process().
TFitResultPtr AnaFillResult::fPCPolarFitRes protected
Definition at line 44 of file AnaFillResult.h.
PolId2TGraphMap AnaFillResult::fPCPolarGraphs protected
Definition at line 38 of file AnaFillResult.h.
Referenced by AppendToPCPolarGraph(), and GetPCPolarGraph().
PolId2TGraphMap AnaFillResult::fPCPolarInjGraphs protected
Definition at line 39 of file AnaFillResult.h.
Referenced by AppendToPCPolarInjGraph(), and GetPCPolarInjGraph().
PolId2ValErrMap AnaFillResult::fPCPolars
Definition at line 56 of file AnaFillResult.h.
Referenced by AnaGlobResult::CalcPolarNorm(), CalcSystJvsCPolar(), CalcSystProfPolar(), GetPCPolar(), Process(), and SetValues().
TargetUId2ValErrMap AnaFillResult::fPCPolarsByTargets
Definition at line 59 of file AnaFillResult.h.
Referenced by Print(), and Process().
PolId2ValErrMap AnaFillResult::fPCPolarUnWs
Definition at line 57 of file AnaFillResult.h.
Referenced by GetPCPolarUnW(), and Process().
PolId2ValErrMap AnaFillResult::fPCProfPolars
Definition at line 60 of file AnaFillResult.h.
Referenced by AnaGlobResult::CalcPolarNorm(), CalcSystProfPolar(), and Process().
PolId2TgtOrient2TGraphMap AnaFillResult::fPCProfRGraphs protected
Definition at line 40 of file AnaFillResult.h.
Referenced by AppendToPCProfRGraph(), and GetPCProfRGraph().
PolId2TgtOrient2TGraphMap AnaFillResult::fPCProfRInjGraphs protected
Definition at line 41 of file AnaFillResult.h.
Referenced by AppendToPCProfRInjGraph(), and GetPCProfRInjGraph().
PolId2TgtOrient2ValErrMap AnaFillResult::fPCProfRs
Definition at line 58 of file AnaFillResult.h.
Referenced by GetPCProfR(), and Process().
PolId2TargetUIdMap AnaFillResult::fPCTargets protected
Definition at line 42 of file AnaFillResult.h.
Referenced by Process().
RingId2ValErrMap AnaFillResult::fPolarRatioU2D
Definition at line 71 of file AnaFillResult.h.
Referenced by CalcPolarRatioU2D(), and GetPolarUDRatio().
RingId2TgtOrient2ValErrMap AnaFillResult::fPolProfPMaxs
Definition at line 81 of file AnaFillResult.h.
Referenced by GetPCProfPMax(), and Process().
RingId2TgtOrient2ValErrMap AnaFillResult::fPolProfPs
Definition at line 82 of file AnaFillResult.h.
Referenced by GetPCProfP(), and Process().
TFitResultPtr AnaFillResult::fPolProfRFitRes protected
Definition at line 45 of file AnaFillResult.h.
RingId2TgtOrient2ValErrMap AnaFillResult::fPolProfRs
Definition at line 80 of file AnaFillResult.h.
Referenced by GetPCProfR(), and Process().
PolId2ValErrMap AnaFillResult::fRampPCPolarRatio
Definition at line 74 of file AnaFillResult.h.
Referenced by CalcRampPCPolarRatio(), and MAsymFillHists::PostFill().
PolId2ValErrMap AnaFillResult::fRotatorPCPolarRatio
Definition at line 73 of file AnaFillResult.h.
Referenced by CalcRotatorPCPolarRatio(), and MAsymFillHists::PostFill().
time_t AnaFillResult::fStartTime protected
Definition at line 34 of file AnaFillResult.h.
Referenced by AddMeasResult(), FitExternGraphs(), GetLumiOffRelTime(), GetLumiOnRelTime(), GetStartTime(), and UpdateExternGraphRange().
PolId2ValErrMap AnaFillResult::fSystJvsCPolar
Definition at line 70 of file AnaFillResult.h.
Referenced by CalcSystJvsCPolar(), and GetSystJvsCPolar().
PolId2ValErrMap AnaFillResult::fSystProfPolar
not used
Definition at line 69 of file AnaFillResult.h.
Referenced by CalcSystProfPolar(), and GetSystProfPolar().
The documentation for this class was generated from the following files:
inc/AnaFillResult.h
src/AnaFillResult.cxx