cnipol: SshLogReader Class Reference
SshLogReader Class Reference
#include <SshLogReader.h>
Public Member Functions
void set_additional_args (const string &additional_args)
void Read (string response, opencdev::result_t *values)
void ExecuteCmd (string cmd, string *response)
virtual void Run (string cmd, opencdev::result_t *values)
virtual void query_timerange (const string &logger, opencdev::cdev_time_t start, opencdev::cdev_time_t end, opencdev::result_t *values)
virtual void query_fill (const string &logger, int fill_id, opencdev::result_t *values)
Protected Attributes
vector< string > fCells
string fAdditionalArgs
Detailed Description
Definition at line 17 of file SshLogReader.h.
Member Function Documentation
void SshLogReader::ExecuteCmd (string cmd, string * response)
Definition at line 172 of file SshLogReader.cxx.
Referenced by Run().
void SshLogReader::query_fill (const string & logger, int fill_id, opencdev::result_t * values) virtual
Definition at line 243 of file SshLogReader.cxx.
void SshLogReader::query_timerange (const string & logger, opencdev::cdev_time_t start, opencdev::cdev_time_t end, opencdev::result_t * values) virtual
Definition at line 236 of file SshLogReader.cxx.
void SshLogReader::Read (string response, opencdev::result_t * values)
Definition at line 113 of file SshLogReader.cxx.
Referenced by Run().
void SshLogReader::Run (string cmd, opencdev::result_t * values) virtual
Definition at line 227 of file SshLogReader.cxx.
Referenced by query_fill(), and query_timerange().
void SshLogReader::set_additional_args (const string & additional_args) inline
Definition at line 34 of file SshLogReader.h.
Member Data Documentation
string SshLogReader::fAdditionalArgs protected
Definition at line 30 of file SshLogReader.h.
Referenced by ExecuteCmd().
vector<string> SshLogReader::fCells protected
Definition at line 29 of file SshLogReader.h.
The documentation for this class was generated from the following files:
inc/SshLogReader.h
src/SshLogReader.cxx