cnipol: AsymAnaInfo Class Reference
AsymAnaInfo Class Reference
This class takes care of the command line options specific to the 'asym' executable.
#include <AsymAnaInfo.h>
Public Types
enum Mode {
MODE_ALPHA = 0x00011000, MODE_NORMAL = 0x00020000, MODE_NO_NORMAL = 0x80020000, MODE_SCALER = 0x00040000,
MODE_RAW = 0x00080000, MODE_RUN = 0x00100000, MODE_TARGET = 0x00200000, MODE_PROFILE = 0x00400000,
MODE_ASYM = 0x00800000, MODE_KINEMA = 0x08000000, MODE_PMT = 0x00000100, MODE_PULSER = 0x00000200,
MODE_STUDIES = 0x00000400, MODE_NO_GAIN_CORRECTION = 0x00000800
}
enum Option { OPTION_AC_DIPOLE_PERIOD = 0x20000004 }
Public Types inherited from AnaInfo
enum Flag {
FLAG_READ_FROM_DB = 0x10000100, FLAG_UPDATE_DB = 0x10000200, FLAG_NO_UPDATE_DB = 0x90000200, FLAG_USE_DB = 0x10000300,
FLAG_CREATE_THUMBS = 0x10000800
}
enum Option {
OPTION_POL_ID = 0x20004000, OPTION_SET_CALIB_ALPHA = 0x20001000, OPTION_DET_DISABLE = 0x20000001, OPTION_SUFFIX = 0x20000002,
OPTION_IMG_FMT = 0x20000006, OPTION_ALPHA_SOURCES = 0x20000003
}
enum Mode { MODE_GRAPH = 0x02000000, MODE_NO_GRAPH = 0x82000000 }
Public Member Functions
AsymAnaInfo ()
AC dipole magnet period in revolutions.
~AsymAnaInfo ()
void SetRunName (std::string runName)
std::string GetRunName () const
std::string GetRawDataFileName () const
virtual std::string GetAnaInfoFileName () const
std::string GetRunConfFileName () const
FILE * GetRunConfFile () const
std::string GetAlphaCalibFile () const
std::string GetRootTreeFileName (UShort_t trid) const
void ProcessOptions (int argc, char **argv)
void VerifyOptions ()
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
void PrintUsage ()
void Update (MseMeasInfoX &run)
Some of this method functionality should better be moved to MeasInfo Update().
std::string GetAlphaCalibRun () const
Bool_t HasAlphaBit () const
Bool_t HasNormalBit () const
Bool_t HasScalerBit () const
Bool_t HasRawBit () const
Bool_t HasRunBit () const
Bool_t HasTargetBit () const
Bool_t HasProfileBit () const
Bool_t HasAsymBit () const
Bool_t HasKinematBit () const
Bool_t HasPmtBit () const
Bool_t HasPulserBit () const
Bool_t HasStudiesBit () const
Bool_t HasNoGainCorrectionBit () const
Public Member Functions inherited from AnaInfo
AnaInfo ()
~AnaInfo ()
std::string GetShortAsymVersion () const
This function provides a version string where git commit id is shortened.
std::string GetSuffix () const
std::string GetResultsDir () const
std::string GetOutDir () const
std::string GetSlowControlLogDir () const
std::string GetImageDir () const
std::string GetStdLogFileName () const
std::string GetRootFileName () const
FILE * GetAnaInfoFile () const
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
Bool_t HasGraphBit () const
Public Attributes
std::string fRunName
ULong_t fAsymModes
std::bitset< 3 > fSaveTrees
std::bitset< N_DETECTORS > fDisabledDetectors
bitmask telling which ROOT trees to save
float MassSigma
bitmask with disabled detector indeces
float MassSigmaAlt
float OneSigma
float tshift
Float_t fThinout
UInt_t fMaxEventsUser
float reference_rate
float target_count_mm
std::string fAlphaCalibRun
FILE * fFileRunConf
uint32_t fAcDipolePeriod
Public Attributes inherited from AnaInfo
std::string fImgFmtName
std::string fAsymVersion
std::string fSuffix
ULong_t fModes
time_t fAnaDateTime
Double_t fAnaTimeReal
Double_t fAnaTimeCpu
Str2StrMap fAsymEnv
FILE * fFileMeasInfo
FILE * fFileStdLog
std::string fFileStdLogName
Bool_t fFlagUseDb
Bool_t fFlagUpdateDb
Bool_t fFlagCreateThumbs
UserGroup_t fUserGroup
Short_t fAlphaSourceCount
Additional Inherited Members
Protected Member Functions inherited from AnaInfo
void Init ()
void MakeOutDir ()
Protected Attributes inherited from AnaInfo
std::string fOutputName
Detailed Description
This class takes care of the command line options specific to the 'asym' executable.
The common options are taken care of by the AnaInfo class.
Definition at line 22 of file AsymAnaInfo.h.
Member Enumeration Documentation
enum AsymAnaInfo::Mode
Enumerator
MODE_ALPHA
MODE_NORMAL
MODE_NO_NORMAL
MODE_SCALER
MODE_RAW
MODE_RUN
MODE_TARGET
MODE_PROFILE
MODE_ASYM
MODE_KINEMA
MODE_PMT
MODE_PULSER
MODE_STUDIES
MODE_NO_GAIN_CORRECTION
Definition at line 27 of file AsymAnaInfo.h.
enum AsymAnaInfo::Option
Enumerator
OPTION_AC_DIPOLE_PERIOD
Definition at line 41 of file AsymAnaInfo.h.
Constructor & Destructor Documentation
AsymAnaInfo::AsymAnaInfo ()
AC dipole magnet period in revolutions.
Definition at line 19 of file AsymAnaInfo.cxx.
AsymAnaInfo::~AsymAnaInfo ()
Definition at line 41 of file AsymAnaInfo.cxx.
Member Function Documentation
string AsymAnaInfo::GetAlphaCalibFile () const
Definition at line 73 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::UpdateCalibrator().
string AsymAnaInfo::GetAlphaCalibRun () const
Definition at line 55 of file AsymAnaInfo.cxx.
Referenced by GetAlphaCalibFile(), EventConfig::PrintAsConfig(), and PrintAsPhp().
string AsymAnaInfo::GetAnaInfoFileName () const virtual
Reimplemented from AnaInfo.
Definition at line 51 of file AsymAnaInfo.cxx.
string AsymAnaInfo::GetRawDataFileName () const
Definition at line 50 of file AsymAnaInfo.cxx.
Referenced by main().
string AsymAnaInfo::GetRootTreeFileName (UShort_t trid) const
Definition at line 87 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateTrees().
FILE * AsymAnaInfo::GetRunConfFile () const
Definition at line 53 of file AsymAnaInfo.cxx.
Referenced by main().
string AsymAnaInfo::GetRunConfFileName () const
Definition at line 52 of file AsymAnaInfo.cxx.
Referenced by VerifyOptions().
string AsymAnaInfo::GetRunName () const
Definition at line 49 of file AsymAnaInfo.cxx.
Referenced by EventConfig::GetSignature(), and AsymRoot::UpdateCalibrator().
Bool_t AsymAnaInfo::HasAlphaBit () const
Definition at line 57 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::Calibrate(), AsymRoot::CreateRootFile(), CnipolTargetHists::Fill(), AsymRoot::FillRunHists(), main(), ProcessRecord(), RawDataReader::ReadDataPassTwo(), AsymRoot::SaveAs(), Update(), AsymRoot::UpdateCalibrator(), Calibrator::UsePlainAlphaGain(), and VerifyOptions().
Bool_t AsymAnaInfo::HasAsymBit () const
Definition at line 64 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile(), and AsymRoot::FillDerived().
Bool_t AsymAnaInfo::HasKinematBit () const
Definition at line 65 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile().
Bool_t AsymAnaInfo::HasNoGainCorrectionBit () const
Definition at line 69 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::Calibrate(), and AsymRoot::UpdateCalibrator().
Bool_t AsymAnaInfo::HasNormalBit () const
Definition at line 58 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile(), AsymRoot::FillDerived(), main(), RawDataReader::ReadDataPassTwo(), and AsymRoot::UpdateCalibrator().
Bool_t AsymAnaInfo::HasPmtBit () const
Definition at line 66 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile().
Bool_t AsymAnaInfo::HasProfileBit () const
Definition at line 63 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile(), AsymRoot::FillDerived(), and AsymRoot::FillProfileHists().
Bool_t AsymAnaInfo::HasPulserBit () const
Definition at line 67 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile().
Bool_t AsymAnaInfo::HasRawBit () const
Definition at line 60 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile().
Bool_t AsymAnaInfo::HasRunBit () const
Definition at line 61 of file AsymAnaInfo.cxx.
Bool_t AsymAnaInfo::HasScalerBit () const
Definition at line 59 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile(), and AsymRoot::FillScallerHists().
Bool_t AsymAnaInfo::HasStudiesBit () const
Definition at line 68 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile().
Bool_t AsymAnaInfo::HasTargetBit () const
Definition at line 62 of file AsymAnaInfo.cxx.
Referenced by AsymRoot::CreateRootFile(), AsymRoot::FillTargetHists(), and ProcessRecord().
void AsymAnaInfo::Print (const Option_t * opt = "") const
Definition at line 365 of file AsymAnaInfo.cxx.
Referenced by main().
void AsymAnaInfo::PrintAsPhp (FILE * f = stdout) const
Definition at line 373 of file AsymAnaInfo.cxx.
Referenced by Print(), and EventConfig::PrintAsPhp().
void AsymAnaInfo::PrintUsage () virtual
Reimplemented from AnaInfo.
Definition at line 390 of file AsymAnaInfo.cxx.
Referenced by ProcessOptions(), and VerifyOptions().
void AsymAnaInfo::ProcessOptions (int argc, char ** argv) virtual
Reimplemented from AnaInfo.
Definition at line 97 of file AsymAnaInfo.cxx.
Referenced by main().
void AsymAnaInfo::SetRunName (std::string runName)
Definition at line 47 of file AsymAnaInfo.cxx.
Referenced by ProcessOptions().
void AsymAnaInfo::Update (MseMeasInfoX & run)
Some of this method functionality should better be moved to MeasInfo Update().
This class should deal only with input command line options.
Definition at line 441 of file AsymAnaInfo.cxx.
Referenced by main().
void AsymAnaInfo::VerifyOptions () virtual
Reimplemented from AnaInfo.
Definition at line 325 of file AsymAnaInfo.cxx.
Referenced by main().
Member Data Documentation
uint32_t AsymAnaInfo::fAcDipolePeriod
Definition at line 59 of file AsymAnaInfo.h.
Referenced by PrintAsPhp(), ProcessOptions(), and MeasInfo::Update().
std::string AsymAnaInfo::fAlphaCalibRun
Definition at line 57 of file AsymAnaInfo.h.
Referenced by GetAlphaCalibFile(), GetAlphaCalibRun(), ProcessOptions(), Update(), and VerifyOptions().
ULong_t AsymAnaInfo::fAsymModes
Definition at line 45 of file AsymAnaInfo.h.
Referenced by HasAlphaBit(), HasAsymBit(), HasKinematBit(), HasNoGainCorrectionBit(), HasNormalBit(), HasPmtBit(), HasProfileBit(), HasPulserBit(), HasRawBit(), HasRunBit(), HasScalerBit(), HasStudiesBit(), HasTargetBit(), PrintAsPhp(), and ProcessOptions().
std::bitset<N_DETECTORS> AsymAnaInfo::fDisabledDetectors
bitmask telling which ROOT trees to save
Definition at line 47 of file AsymAnaInfo.h.
Referenced by PrintAsPhp(), ProcessOptions(), and VerifyOptions().
FILE* AsymAnaInfo::fFileRunConf
Definition at line 58 of file AsymAnaInfo.h.
Referenced by GetRunConfFile(), main(), VerifyOptions(), and ~AsymAnaInfo().
UInt_t AsymAnaInfo::fMaxEventsUser
Definition at line 54 of file AsymAnaInfo.h.
Referenced by PrintAsPhp(), and ProcessOptions().
std::string AsymAnaInfo::fRunName
Definition at line 44 of file AsymAnaInfo.h.
Referenced by GetRawDataFileName(), GetRootTreeFileName(), GetRunName(), PrintAsPhp(), SetRunName(), and VerifyOptions().
std::bitset<3> AsymAnaInfo::fSaveTrees
Definition at line 46 of file AsymAnaInfo.h.
Referenced by AsymRoot::AddChannelEvent(), AsymRoot::CreateTrees(), AsymRoot::Finalize(), main(), PrintAsPhp(), ProcessOptions(), AsymRoot::SaveChannelTrees(), and AsymRoot::SaveEventTree().
Float_t AsymAnaInfo::fThinout
Definition at line 53 of file AsymAnaInfo.h.
Referenced by PrintAsPhp(), and ProcessOptions().
float AsymAnaInfo::MassSigma
bitmask with disabled detector indeces
Definition at line 48 of file AsymAnaInfo.h.
Referenced by CompleteHistogram(), AsymCalculator::PrintRunResults(), and ProcessOptions().
float AsymAnaInfo::MassSigmaAlt
Definition at line 49 of file AsymAnaInfo.h.
Referenced by CompleteHistogram(), and AsymCalculator::PrintRunResults().
float AsymAnaInfo::OneSigma
Definition at line 51 of file AsymAnaInfo.h.
Referenced by TshiftFinder().
float AsymAnaInfo::reference_rate
Definition at line 55 of file AsymAnaInfo.h.
Referenced by AsymCalculator::CalcStatistics(), and MeasInfo::PrintConfig().
float AsymAnaInfo::target_count_mm
Definition at line 56 of file AsymAnaInfo.h.
Referenced by MeasInfo::PrintConfig(), and ProcessRecordPCTarget().
float AsymAnaInfo::tshift
Definition at line 52 of file AsymAnaInfo.h.
Referenced by cnipol_toolkit::KinemaReconstruction(), MeasInfo::PrintConfig(), and ProcessOptions().
The documentation for this class was generated from the following files:
inc/AsymAnaInfo.h
src/AsymAnaInfo.cxx