cnipol: src/malpha.cxx File Reference
malpha.cxx File Reference
#include <cstdlib>
#include <string>
#include <map>
#include <vector>
#include <algorithm>
#include <numeric>
#include <stdint.h>
#include "malpha.h"
#include "TEnv.h"
#include "TROOT.h"
#include "TLegend.h"
#include <opencdev.h>
#include <SshLogReader.h>
#include <CachingLogReader.h>
#include "MAlphaAnaInfo.h"
#include "AsymHeader.h"
#include "MeasInfo.h"
#include "BiasCurrentUtil.h"
#include "RunConfig.h"
#include "DrawObjContainer.h"
#include "utils/utils.h"
Classes
struct ResultMean
Macros
#define DoBCGainFit(g) ((g)->Fit("pol1", "QS", "", -50., -0.1));
Typedefs
typedef double Time
typedef string RunName
typedef int DetectorId
Functions
void FillFromHist (TH1F *h, double startTime, ResultMean &result, ResultMean &result_err)
void FillDeviceMaxMin (map< Short_t, ResultMean > &results)
void PlotMean (DrawObjContainer *oc, const char *name, ResultMean &result, ResultMean &result_err, map< Time, RunName > &runNameD, double min_startTime, double max_startTime)
void PlotCorrelation (DrawObjContainer *oc, const char *name, ResultMean &r1, ResultMean &r1_err, ResultMean &r2, ResultMean &r2_err)
vector< double > DoAmGainCorrection (ResultMean &rhAmGain, ResultMean &rhAmGainErr, ResultMean &rBiasCurrent, ResultMean &rhAmGainCorrected, ResultMean &rhAmGainCorrectedErr)
Takes in a AmGain plot.
void FillDetectorAverage (ResultMean &result, ResultMean &result_err, double startTime)
void FillBiasCurrent (opencdev::LogReader *log_reader, EPolarimeterId polId, double startTime, double endTime, map< Short_t, ResultMean > &rBiasCurrent, map< Short_t, ResultMean > &rBiasCurrentErr)
void FillBeamCurrent (opencdev::LogReader *log_reader, int fill_id, EPolarimeterId polId, double startTime, map< Short_t, ResultMean > &rBeamCurrent, map< Short_t, ResultMean > &rBeamCurrentErr)
void SetupSignature (DrawObjContainer *oc, MAlphaAnaInfo &mAlphaAnaInfo)
int main (int argc, char *argv[])
Macro Definition Documentation
#define DoBCGainFit (g) ((g)->Fit("pol1", "QS", "", -50., -0.1));
Definition at line 332 of file malpha.cxx.
Referenced by DoAmGainCorrection(), and PlotCorrelation().
Typedef Documentation
typedef int DetectorId
Definition at line 33 of file malpha.cxx.
typedef string RunName
Definition at line 32 of file malpha.cxx.
typedef double Time
Definition at line 31 of file malpha.cxx.
Function Documentation
vector<double> DoAmGainCorrection (ResultMean & rhAmGain, ResultMean & rhAmGainErr, ResultMean & rBiasCurrent, ResultMean & rhAmGainCorrected, ResultMean & rhAmGainCorrectedErr)
Takes in a AmGain plot.
Calculates the slope of the Gain vs BiasCurrent correlation. Uses that slope value and BiasCurrent values to make a plot AmGainCorrected containing the corrected values.
Definition at line 398 of file malpha.cxx.
Referenced by main().
void FillBeamCurrent (opencdev::LogReader * log_reader, int fill_id, EPolarimeterId polId, double startTime, map< Short_t, ResultMean > & rBeamCurrent, map< Short_t, ResultMean > & rBeamCurrentErr)
Definition at line 485 of file malpha.cxx.
Referenced by main().
void FillBiasCurrent (opencdev::LogReader * log_reader, EPolarimeterId polId, double startTime, double endTime, map< Short_t, ResultMean > & rBiasCurrent, map< Short_t, ResultMean > & rBiasCurrentErr)
Definition at line 471 of file malpha.cxx.
Referenced by main().
void FillDetectorAverage (ResultMean & result, ResultMean & result_err, double startTime)
Definition at line 453 of file malpha.cxx.
Referenced by FillBeamCurrent(), and FillBiasCurrent().
void FillDeviceMaxMin (map< Short_t, ResultMean > & results)
Definition at line 85 of file malpha.cxx.
Referenced by main().
void FillFromHist (TH1F * h, double startTime, ResultMean & result, ResultMean & result_err)
Definition at line 46 of file malpha.cxx.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 551 of file malpha.cxx.
void PlotCorrelation (DrawObjContainer * oc, const char * name, ResultMean & r1, ResultMean & r1_err, ResultMean & r2, ResultMean & r2_err)
Definition at line 336 of file malpha.cxx.
Referenced by main().
void PlotMean (DrawObjContainer * oc, const char * name, ResultMean & result, ResultMean & result_err, map< Time, RunName > & runNameD, double min_startTime, double max_startTime)
Definition at line 121 of file malpha.cxx.
Referenced by main().
void SetupSignature (DrawObjContainer * oc, MAlphaAnaInfo & mAlphaAnaInfo)
Definition at line 535 of file malpha.cxx.
Referenced by main().