cnipol: inc/MseFillPolar.h File Reference
MseFillPolar.h File Reference
#include <stdio.h>
#include "mysql++.h"
#include "ssqls.h"
#include "TObject.h"
#include "RunConfig.h"
#include "AnaFillResult.h"
Macros
#define MYSQLPP_SSQLS_NO_STATICS
#define MseFillPolar_h
Functions
sql_create_22(MseFillPolar, 1, 2, mysqlpp::sql_int_unsigned, fill, mysqlpp::sql_datetime, start_time, mysqlpp::sql_smallint, type, mysqlpp::sql_float, beam_energy, mysqlpp::sql_decimal, polar_blue_p0, mysqlpp::sql_decimal, polar_blue_decay, mysqlpp::sql_float, polar_yellow_p0, mysqlpp::sql_float, polar_yellow_p0_err, mysqlpp::sql_float, polar_yellow_decay, mysqlpp::sql_float, polar_yellow_decay_err, mysqlpp::sql_float, polar_blue_hjet, mysqlpp::sql_float, polar_blue_hjet_err, mysqlpp::sql_float, polar_yellow_hjet, mysqlpp::sql_float, polar_yellow_hjet_err, mysqlpp::sql_float, polar_blue_1, mysqlpp::sql_float, polar_blue_1_err, mysqlpp::sql_float, polar_blue_2, mysqlpp::sql_float, polar_blue_2_err, mysqlpp::sql_float, polar_yellow_1, mysqlpp::sql_float, polar_yellow_1_err, mysqlpp::sql_float, polar_yellow_2, mysqlpp::sql_float, polar_yellow_2_err) class MseFillPolarX ~MseFillPolarX ()
MseFillPolarX (const mysqlpp::sql_int_unsigned &p1)
MseFillPolarX (const mysqlpp::Row &row)
void Init ()
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
void SetValues (const AnaFillResult &fr)
Macro Definition Documentation
#define MseFillPolar_h
Definition at line 6 of file MseFillPolar.h.
#define MYSQLPP_SSQLS_NO_STATICS
Definition at line 2 of file MseFillPolar.h.
Function Documentation
void Init ()
Referenced by AnaInfo::AnaInfo(), AsymAnaInfo::AsymAnaInfo(), MAlphaAnaInfo::MAlphaAnaInfo(), MAsymAnaInfo::MAsymAnaInfo(), MseFillPolarNewX(), MseFillPolarX(), MseFillProfileNewX(), MseFillProfileX(), and MseMeasInfoX().
MseFillPolarX::MseFillPolarX (const mysqlpp::sql_int_unsigned & p1)
Definition at line 27 of file MseFillPolar.cxx.
Referenced by AsymDbSql::SelectFillPolar().
MseFillPolarX (const mysqlpp::Row & row)
Definition at line 55 of file MseFillPolar.h.
void Print (const Option_t * opt = "") const
void PrintAsPhp (FILE * f = stdout) const
void MseFillProfileX::SetValues (const AnaFillResult & fr)
Definition at line 92 of file MseFillPolar.cxx.
Referenced by SetValuesHJ(), and SetValuesPC().
MseFillPolarX::~MseFillPolarX ()
Definition at line 21 of file MseFillPolar.cxx.