cnipol: cnipol_toolkit Namespace Reference
cnipol_toolkit Namespace Reference
Functions
float ekin (float edep, float dthick)
Parameterized function to convert the measured deposited energy (edep) to the kinetic energy of 12C for a given deadlayer thickness (dthick).
void KinemaReconstruction (processEvent *event, recordConfigRhicStruct *gConfigInfo, int chId, float &edepo, float &e, float &t, float &delt, float &Mass)
Calculates kinematic energy from measured ADC and TDC values.
void KinemaReconstruction (int Mode, processEvent *event, recordConfigRhicStruct *cfginfo, int st, float &edepo, float &e, float &t, float &delt, float &Mass)
void SpinTuneOutput (int bid, double si)
Function Documentation
float cnipol_toolkit::ekin (float edep, float dthick)
Parameterized function to convert the measured deposited energy (edep) to the kinetic energy of 12C for a given deadlayer thickness (dthick).
Ekin = p0 + p1*Edep + p2*Edep^2 + p3*Edep^3 + p4*Edep^4
For more details about the energy loss model see Appendix A in http://www4.rcf.bnl.gov/~cnipol/Documentations/Files/NIM_080523.pdf
Definition at line 20 of file cnipol_toolkit.cxx.
Referenced by CalcInvertKinema(), ChannelEvent::GetFunnyEnergyA(), ChannelEvent::GetKinEnergyAEDepend(), ChannelEvent::GetKinEnergyAEDependAverage(), ChannelEvent::GetKinEnergyAEstimateEDepend(), KinemaReconstruction(), and main().
void cnipol_toolkit::KinemaReconstruction (int Mode, processEvent * event, recordConfigRhicStruct * cfginfo, int st, float & edepo, float & e, float & t, float & delt, float & Mass)
void cnipol_toolkit::KinemaReconstruction (processEvent * event, recordConfigRhicStruct * gConfigInfo, int chId, float & edepo, float & e, float & t, float & delt, float & Mass)
Calculates kinematic energy from measured ADC and TDC values.
Parameters
[in] chId Polarimeter channel id starting with 1
[out] edepo Energy deposited in the detector strip
[out] e Kinetic energy of a carbon particle
[out] t Time of flight in ns
[out] delt Difference between the observed and
Author
Itaru Nakagawa
Dmitri Smirnov d.s@p.nosp@m.lexo.nosp@m.os.co.nosp@m.m
Definition at line 59 of file cnipol_toolkit.cxx.
void cnipol_toolkit::SpinTuneOutput (int bid, double si)