cnipol: /direct/eic+u/dsmirnov/cnipol/src/AsymDbFile.cxx File Reference
AsymDbFile.cxx File Reference
#include "AsymDbFile.h"
#include "TObjArray.h"
#include "TObjString.h"
#include "TPRegexp.h"
#include "TString.h"
#include "TSystem.h"
#include "AnaInfo.h"
#include "MeasInfo.h"
Functions
void readdb (double RUNID)
void StripHandler (int st, int flag)
void SetDefault ()
int FindDisableStrip ()
void BunchHandler (int bunch, int flag)
int FindDisableBunch ()
int MatchPolarimetry (double ThisRunID, double RefRunID)
int ContinueScan (double ThisRunID, double RunID)
void PrintRunDB ()
string GetVariables (string str)
Variables
int ProcessStrip [NSTRIP]
int ProcessBunch [NBUNCH]
Function Documentation
void BunchHandler (int bunch, int flag)
Definition at line 615 of file AsymDbFile.cxx.
Referenced by readdb().
int ContinueScan (double ThisRunID, double RunID)
Definition at line 671 of file AsymDbFile.cxx.
int FindDisableBunch ()
Definition at line 628 of file AsymDbFile.cxx.
int FindDisableStrip ()
Definition at line 598 of file AsymDbFile.cxx.
string GetVariables (string str)
Definition at line 718 of file AsymDbFile.cxx.
Referenced by readdb().
int MatchPolarimetry (double ThisRunID, double RefRunID)
Definition at line 646 of file AsymDbFile.cxx.
Referenced by readdb().
void PrintRunDB ()
Definition at line 700 of file AsymDbFile.cxx.
Referenced by readdb().
void readdb (double RUNID)
Definition at line 395 of file AsymDbFile.cxx.
Referenced by getPreviousRun(), and main().
void SetDefault ()
Definition at line 572 of file AsymDbFile.cxx.
Referenced by readdb().
void StripHandler (int st, int flag)
Definition at line 560 of file AsymDbFile.cxx.
Referenced by readdb().
Variable Documentation
int ProcessBunch[NBUNCH]
Definition at line 16 of file AsymDbFile.cxx.
Referenced by BunchHandler(), FindDisableBunch(), and SetDefault().
int ProcessStrip[NSTRIP]
Definition at line 15 of file AsymDbFile.cxx.
Referenced by FindDisableStrip(), SetDefault(), and StripHandler().