cnipol: /direct/eic+u/dsmirnov/cnipol/src/AsymCalculator.cxx File Reference
AsymCalculator.cxx File Reference
#include "AsymCalculator.h"
#include <math.h>
#include "TF1.h"
#include "TF2.h"
#include "TLatex.h"
#include "TMath.h"
#include "AsymRoot.h"
#include "AnaInfo.h"
#include "AnaMeasResult.h"
#include "ChannelCalib.h"
#include "MeasInfo.h"
#include "TargetInfo.h"
#include "MseMeasInfo.h"
#include "utils/utils.h"
#include "utils/ValErrPair.h"
Functions
void CompleteHistogram ()
float ProfileError (float x)
float TshiftFinder (int Mode, int FeedBackLevel)
void FillAsymmetryHistgram (string mode, int sign, int N, float *A, float *dA)
void calcBunchAsymmetryAverage ()
void calcLRAsymmetry (float X90[2], float X45_tmp[2], float &A, float &dA)
Function Documentation
void calcBunchAsymmetryAverage ()
Definition at line 1457 of file AsymCalculator.cxx.
Referenced by AsymCalculator::CalcBunchAsym().
void calcLRAsymmetry (float X90[2], float X45_tmp[2], float & A, float & dA)
Definition at line 1513 of file AsymCalculator.cxx.
Referenced by calcBunchAsymmetryAverage().
void CompleteHistogram ()
Definition at line 49 of file AsymCalculator.cxx.
void FillAsymmetryHistgram (string mode, int sign, int N, float * A, float * dA)
Definition at line 1145 of file AsymCalculator.cxx.
Referenced by AsymCalculator::CalcBunchAsym().
float ProfileError (float x)
Definition at line 957 of file AsymCalculator.cxx.
Referenced by AsymCalculator::CalcStatistics().
float TshiftFinder (int Mode, int FeedBackLevel)
Definition at line 1014 of file AsymCalculator.cxx.