cnipol: inc/AsymCommon.h File Reference
AsymCommon.h File Reference
#include <iostream>
#include <iterator>
#include <map>
#include <set>
#include <string>
#include <sstream>
#include <utility>
#include "TH1.h"
#include "TGraph.h"
#include "TGraphErrors.h"
#include "TFitResultPtr.h"
#include "rpoldata.h"
#include "AsymHeader.h"
#include "utils/ValErrPair.h"
Classes
struct processEvent
struct asymStruct
struct ErrorDetector
struct atdata_struct
class RunConst
struct StructMask
struct StructAnomaly
struct StructUnrecognized
struct StructSinPhi
struct StructExtInput
struct StructAverage
struct StructHistStat
struct StructFeedBack
struct StructFlag
struct StructStripCounter
struct StructStripCounterTgt
struct StructCounter
struct StructCounterTgt
struct StructBunchPattern
struct StructHist
struct BunchAsym
struct BunchAsym::Ave
struct StructSpeLumi
struct StructStrip
struct StructEnergyCorr
struct StructStripCheck
struct StructBunch
struct StructBunchCheck
Typedefs
typedef std::map< std::string,
std::string > Str2StrMap
typedef std::map< std::string,
TFitResultPtr > Str2FitResMap
typedef std::map< ESpinState,
TFitResultPtr > Spin2FitResMap
typedef std::pair< UShort_t,
UShort_t > DetLRPair
typedef std::set< DetLRPair > DetLRSet
typedef std::map
< EPolarimeterId, ValErrSet > PolId2ValErrSet
typedef PolId2ValErrSet::iterator PolId2ValErrSetIter
typedef
PolId2ValErrSet::const_iterator PolId2ValErrSetConstIter
typedef std::map
< EPolarimeterId, ValErrPair > PolId2ValErrMap
typedef PolId2ValErrMap::iterator PolId2ValErrMapIter
typedef
PolId2ValErrMap::const_iterator PolId2ValErrMapConstIter
typedef std::map
< EPolarimeterId, TGraph * > PolId2TGraphMap
typedef PolId2TGraphMap::iterator PolId2TGraphMapIter
typedef
PolId2TGraphMap::const_iterator PolId2TGraphMapConstIter
typedef std::map
< EPolarimeterId, TargetUId > PolId2TargetUIdMap
typedef
PolId2TargetUIdMap::iterator PolId2TargetUIdMapIter
typedef
PolId2TargetUIdMap::const_iterator PolId2TargetUIdMapConstIter
typedef std::map
< ETargetOrient, TGraph * > TgtOrient2TGraphMap
typedef
TgtOrient2TGraphMap::iterator TgtOrient2TGraphMapIter
typedef
TgtOrient2TGraphMap::const_iterator TgtOrient2TGraphMapConstIter
typedef std::map< EBeamId,
ValErrSet > BeamId2ValErrSet
typedef BeamId2ValErrSet::iterator BeamId2ValErrSetIter
typedef
BeamId2ValErrSet::const_iterator BeamId2ValErrSetConstIter
typedef std::map< EBeamId,
ValErrPair > BeamId2ValErrMap
typedef BeamId2ValErrMap::iterator BeamId2ValErrMapIter
typedef
BeamId2ValErrMap::const_iterator BeamId2ValErrMapConstIter
typedef std::map
< ETargetOrient, ValErrPair > TgtOrient2ValErrMap
typedef
TgtOrient2ValErrMap::iterator TgtOrient2ValErrMapIter
typedef
TgtOrient2ValErrMap::const_iterator TgtOrient2ValErrMapConstIter
typedef std::map
< EPolarimeterId,
TgtOrient2ValErrMap > PolId2TgtOrient2ValErrMap
typedef
PolId2TgtOrient2ValErrMap::iterator PolId2TgtOrient2ValErrMapIter
typedef
PolId2TgtOrient2ValErrMap::const_iterator PolId2TgtOrient2ValErrMapConstIter
typedef std::map
< EPolarimeterId,
TgtOrient2TGraphMap > PolId2TgtOrient2TGraphMap
typedef
PolId2TgtOrient2TGraphMap::iterator PolId2TgtOrient2TGraphMapIter
typedef
PolId2TgtOrient2TGraphMap::const_iterator PolId2TgtOrient2TGraphMapConstIter
typedef std::map< EBeamId,
TgtOrient2ValErrMap > BeamId2TgtOrient2ValErrMap
typedef
BeamId2TgtOrient2ValErrMap::iterator BeamId2TgtOrient2ValErrMapIter
typedef
BeamId2TgtOrient2ValErrMap::const_iterator BeamId2TgtOrient2ValErrMapConstIter
typedef std::map< std::string,
EBeamId > String2BeamIdMap
typedef String2BeamIdMap::iterator String2BeamIdMapIter
typedef
String2BeamIdMap::const_iterator String2BeamIdMapConstIter
typedef std::map< ERingId,
ValErrSet > RingId2ValErrSet
typedef RingId2ValErrSet::iterator RingId2ValErrSetIter
typedef
RingId2ValErrSet::const_iterator RingId2ValErrSetConstIter
typedef std::map< ERingId,
ValErrPair > RingId2ValErrMap
typedef RingId2ValErrMap::iterator RingId2ValErrMapIter
typedef
RingId2ValErrMap::const_iterator RingId2ValErrMapConstIter
typedef std::map< ERingId,
TgtOrient2ValErrMap > RingId2TgtOrient2ValErrMap
typedef
RingId2TgtOrient2ValErrMap::iterator RingId2TgtOrient2ValErrMapIter
typedef
RingId2TgtOrient2ValErrMap::const_iterator RingId2TgtOrient2ValErrMapConstIter
typedef std::map< std::string,
ERingId > String2RingIdMap
typedef String2RingIdMap::iterator String2RingIdMapIter
typedef std::map< std::string,
ETargetOrient > String2TgtOrientMap
typedef
String2TgtOrientMap::iterator String2TgtOrientMapIter
typedef std::map< std::string,
UShort_t > String2TargetIdMap
typedef
String2TargetIdMap::iterator String2TargetIdMapIter
typedef std::set< EBeamId > BeamIdSet
typedef BeamIdSet::iterator BeamIdSetIter
typedef BeamIdSet::const_iterator BeamIdConstIter
typedef std::set< ERingId > RingIdSet
typedef RingIdSet::iterator RingIdSetIter
typedef RingIdSet::const_iterator RingIdConstIter
typedef std::set< ETargetOrient > TargetOrientSet
typedef TargetOrientSet::iterator TargetOrientSetIter
typedef std::set< EBeamEnergy > BeamEnergySet
typedef BeamEnergySet::iterator BeamEnergySetIter
typedef std::set< ESpinState > SpinStateSet
typedef SpinStateSet::iterator SpinStateSetIter
typedef std::set< EAsymType > AsymTypeSet
typedef AsymTypeSet::iterator AsymTypeSetIter
typedef std::set< EPolarimeterId > PolarimeterIdSet
typedef PolarimeterIdSet::iterator PolarimeterIdSetIter
typedef
PolarimeterIdSet::const_iterator PolarimeterIdSetConstIter
typedef std::set< UShort_t > ChannelSet
typedef ChannelSet::iterator ChannelSetIter
typedef ChannelSet::const_iterator ChannelSetConstIter
Enumerations
enum EPolarimeterId {
kB1U = 0, kY1D = 1, kB2D = 2, kY2U = 3,
kUNKNOWN_POLID, kHJET = 10
}
enum EBeamId { kBLUE_BEAM = 1, kYELLOW_BEAM = 2, kUNKNOWN_BEAM }
enum ERingId { kBLUE_RING = 1, kYELLOW_RING = 2, kUNKNOWN_RING }
enum EStreamId { kUPSTREAM = 1, kDOWNSTREAM = 2, kUNKNOWN_STREAM }
enum ETargetOrient { kTARGET_H = 0, kTARGET_V = 1, kUNKNOWN_ORIENT }
enum EBeamEnergy { kINJECTION = 24, kBEAM_ENERGY_100 = 100, kBEAM_ENERGY_250 = 250, kBEAM_ENERGY_255 = 255 }
enum ESpinState { kSPIN_DOWN = -1, kSPIN_NULL = 0, kSPIN_UP = +1 }
enum EAsymType { kPHYS_ASYM = 1, kGEOM_ASYM = 2, kLUMI_ASYM = 3 }
enum EFillType { kFILLTYPE_UNKNOWN = 0, kFILLTYPE_PHYSICS }
Functions
std::ostream & operator<< (std::ostream &os, const TgtOrient2ValErrMap &vep)
void hhbook1d_ (int *, char *, int *, float *, float *, int)
void hhbook2d_ (int *, char *, int *, float *, float *, int *, float *, float *, int)
void hhf1_ (int *, float *, float *)
void hhf2_ (int *, float *, float *, float *)
void hhlimit_ (int *)
void hhropen_ (int *, char *, char *, char *, int *, int *, int, int, int)
void hhrend_ (char *, int)
void hhrout_ (int *, int *, char *, int)
void hhrammar_ (float *, int *)
void hhrebin_ (int *, float *, float *, float *, float *, int *, int *, int *)
void hhpak_ (int *, float *)
void hhpake_ (int *, float *)
float hhmax_ (int *)
float hhstati_ (int *, int *, char *, int *, int)
void hfith_ (int *, char *, char *, int *, float *, float *, float *, float *, float *, float *, int, int)
void hfithn_ (int *, char *, char *, int *, float *, float *, float *, float *, float *, float *, int, int)
float GetMax (int N, float A[])
float GetMin (int N, float A[])
void GetMinMax (int N, float A[], float margin, float &min, float &max)
Return Minimum and Maximum from array A[N].
void GetMinMaxOption (float prefix, int N, float A[], float margin, float &min, float &max)
void DrawText (TH1 *h, float x, float y, int color, char *text)
void DrawLine (TH1 *h, float x1, float y1, float x2, float y2, int color, int lstyle, int lwidth)
void DrawHorizLine (TH1 *h, float x1, float x2, float y, int color, int lstyle, int lwidth)
void DrawVertLine (TH1 *h, float x, float y, int color, int lwidth)
void binary_zero (int n, int mb)
TGraphErrors * AsymmetryGraph (int Mode, int N, float *x, float *y, float *ex, float *ey)
void ReadRampTiming (char *filename)
template<class T >
std::string VecAsPhpArray (const std::vector< T > &v)
template<class T >
std::string SetAsPhpArray (const std::set< T > &s)
template<class Key , class T >
std::string MapAsPhpArray (const std::map< Key, T > &m)
std::string PairAsPhpArray (const ValErrPair &p)
Typedef Documentation
typedef std::set<EAsymType> AsymTypeSet
Definition at line 133 of file AsymCommon.h.
typedef AsymTypeSet::iterator AsymTypeSetIter
Definition at line 134 of file AsymCommon.h.
typedef std::set<EBeamEnergy> BeamEnergySet
Definition at line 127 of file AsymCommon.h.
typedef BeamEnergySet::iterator BeamEnergySetIter
Definition at line 128 of file AsymCommon.h.
typedef std::map<EBeamId, TgtOrient2ValErrMap> BeamId2TgtOrient2ValErrMap
Definition at line 82 of file AsymCommon.h.
typedef BeamId2TgtOrient2ValErrMap::const_iterator BeamId2TgtOrient2ValErrMapConstIter
Definition at line 84 of file AsymCommon.h.
typedef BeamId2TgtOrient2ValErrMap::iterator BeamId2TgtOrient2ValErrMapIter
Definition at line 83 of file AsymCommon.h.
typedef std::map<EBeamId, ValErrPair> BeamId2ValErrMap
Definition at line 66 of file AsymCommon.h.
typedef BeamId2ValErrMap::const_iterator BeamId2ValErrMapConstIter
Definition at line 68 of file AsymCommon.h.
typedef BeamId2ValErrMap::iterator BeamId2ValErrMapIter
Definition at line 67 of file AsymCommon.h.
typedef std::map<EBeamId, ValErrSet> BeamId2ValErrSet
Definition at line 63 of file AsymCommon.h.
typedef BeamId2ValErrSet::const_iterator BeamId2ValErrSetConstIter
Definition at line 65 of file AsymCommon.h.
typedef BeamId2ValErrSet::iterator BeamId2ValErrSetIter
Definition at line 64 of file AsymCommon.h.
typedef BeamIdSet::const_iterator BeamIdConstIter
Definition at line 118 of file AsymCommon.h.
typedef std::set<EBeamId> BeamIdSet
Definition at line 116 of file AsymCommon.h.
typedef BeamIdSet::iterator BeamIdSetIter
Definition at line 117 of file AsymCommon.h.
typedef std::set<UShort_t> ChannelSet
Definition at line 141 of file AsymCommon.h.
typedef ChannelSet::const_iterator ChannelSetConstIter
Definition at line 143 of file AsymCommon.h.
typedef ChannelSet::iterator ChannelSetIter
Definition at line 142 of file AsymCommon.h.
typedef std::pair<UShort_t, UShort_t> DetLRPair
Definition at line 39 of file AsymCommon.h.
typedef std::set<DetLRPair> DetLRSet
Definition at line 40 of file AsymCommon.h.
typedef std::set<EPolarimeterId> PolarimeterIdSet
Definition at line 136 of file AsymCommon.h.
typedef PolarimeterIdSet::const_iterator PolarimeterIdSetConstIter
Definition at line 138 of file AsymCommon.h.
typedef PolarimeterIdSet::iterator PolarimeterIdSetIter
Definition at line 137 of file AsymCommon.h.
typedef std::map<EPolarimeterId, TargetUId> PolId2TargetUIdMap
Definition at line 54 of file AsymCommon.h.
typedef PolId2TargetUIdMap::const_iterator PolId2TargetUIdMapConstIter
Definition at line 56 of file AsymCommon.h.
typedef PolId2TargetUIdMap::iterator PolId2TargetUIdMapIter
Definition at line 55 of file AsymCommon.h.
typedef std::map<EPolarimeterId, TGraph*> PolId2TGraphMap
Definition at line 50 of file AsymCommon.h.
typedef PolId2TGraphMap::const_iterator PolId2TGraphMapConstIter
Definition at line 52 of file AsymCommon.h.
typedef PolId2TGraphMap::iterator PolId2TGraphMapIter
Definition at line 51 of file AsymCommon.h.
typedef std::map<EPolarimeterId, TgtOrient2TGraphMap> PolId2TgtOrient2TGraphMap
Definition at line 78 of file AsymCommon.h.
typedef PolId2TgtOrient2TGraphMap::const_iterator PolId2TgtOrient2TGraphMapConstIter
Definition at line 80 of file AsymCommon.h.
typedef PolId2TgtOrient2TGraphMap::iterator PolId2TgtOrient2TGraphMapIter
Definition at line 79 of file AsymCommon.h.
typedef std::map<EPolarimeterId, TgtOrient2ValErrMap> PolId2TgtOrient2ValErrMap
Definition at line 74 of file AsymCommon.h.
typedef PolId2TgtOrient2ValErrMap::const_iterator PolId2TgtOrient2ValErrMapConstIter
Definition at line 76 of file AsymCommon.h.
typedef PolId2TgtOrient2ValErrMap::iterator PolId2TgtOrient2ValErrMapIter
Definition at line 75 of file AsymCommon.h.
typedef std::map<EPolarimeterId, ValErrPair> PolId2ValErrMap
Definition at line 46 of file AsymCommon.h.
typedef PolId2ValErrMap::const_iterator PolId2ValErrMapConstIter
Definition at line 48 of file AsymCommon.h.
typedef PolId2ValErrMap::iterator PolId2ValErrMapIter
Definition at line 47 of file AsymCommon.h.
typedef std::map<EPolarimeterId, ValErrSet> PolId2ValErrSet
Definition at line 42 of file AsymCommon.h.
typedef PolId2ValErrSet::const_iterator PolId2ValErrSetConstIter
Definition at line 44 of file AsymCommon.h.
typedef PolId2ValErrSet::iterator PolId2ValErrSetIter
Definition at line 43 of file AsymCommon.h.
typedef std::map<ERingId, TgtOrient2ValErrMap> RingId2TgtOrient2ValErrMap
Definition at line 101 of file AsymCommon.h.
typedef RingId2TgtOrient2ValErrMap::const_iterator RingId2TgtOrient2ValErrMapConstIter
Definition at line 103 of file AsymCommon.h.
typedef RingId2TgtOrient2ValErrMap::iterator RingId2TgtOrient2ValErrMapIter
Definition at line 102 of file AsymCommon.h.
typedef std::map<ERingId, ValErrPair> RingId2ValErrMap
Definition at line 94 of file AsymCommon.h.
typedef RingId2ValErrMap::const_iterator RingId2ValErrMapConstIter
Definition at line 96 of file AsymCommon.h.
typedef RingId2ValErrMap::iterator RingId2ValErrMapIter
Definition at line 95 of file AsymCommon.h.
typedef std::map<ERingId, ValErrSet> RingId2ValErrSet
Definition at line 91 of file AsymCommon.h.
typedef RingId2ValErrSet::const_iterator RingId2ValErrSetConstIter
Definition at line 93 of file AsymCommon.h.
typedef RingId2ValErrSet::iterator RingId2ValErrSetIter
Definition at line 92 of file AsymCommon.h.
typedef RingIdSet::const_iterator RingIdConstIter
Definition at line 122 of file AsymCommon.h.
typedef std::set<ERingId> RingIdSet
Definition at line 120 of file AsymCommon.h.
typedef RingIdSet::iterator RingIdSetIter
Definition at line 121 of file AsymCommon.h.
typedef std::map<ESpinState, TFitResultPtr> Spin2FitResMap
Definition at line 38 of file AsymCommon.h.
typedef std::set<ESpinState> SpinStateSet
Definition at line 130 of file AsymCommon.h.
typedef SpinStateSet::iterator SpinStateSetIter
Definition at line 131 of file AsymCommon.h.
typedef std::map<std::string, TFitResultPtr> Str2FitResMap
Definition at line 37 of file AsymCommon.h.
typedef std::map<std::string, std::string> Str2StrMap
Definition at line 36 of file AsymCommon.h.
typedef std::map<std::string, EBeamId> String2BeamIdMap
Definition at line 86 of file AsymCommon.h.
typedef String2BeamIdMap::const_iterator String2BeamIdMapConstIter
Definition at line 88 of file AsymCommon.h.
typedef String2BeamIdMap::iterator String2BeamIdMapIter
Definition at line 87 of file AsymCommon.h.
typedef std::map<std::string, ERingId> String2RingIdMap
Definition at line 106 of file AsymCommon.h.
typedef String2RingIdMap::iterator String2RingIdMapIter
Definition at line 107 of file AsymCommon.h.
typedef std::map<std::string, UShort_t> String2TargetIdMap
Definition at line 112 of file AsymCommon.h.
typedef String2TargetIdMap::iterator String2TargetIdMapIter
Definition at line 113 of file AsymCommon.h.
typedef std::map<std::string, ETargetOrient> String2TgtOrientMap
Definition at line 109 of file AsymCommon.h.
typedef String2TgtOrientMap::iterator String2TgtOrientMapIter
Definition at line 110 of file AsymCommon.h.
typedef std::set<ETargetOrient> TargetOrientSet
Definition at line 124 of file AsymCommon.h.
typedef TargetOrientSet::iterator TargetOrientSetIter
Definition at line 125 of file AsymCommon.h.
typedef std::map<ETargetOrient, TGraph*> TgtOrient2TGraphMap
Definition at line 58 of file AsymCommon.h.
typedef TgtOrient2TGraphMap::const_iterator TgtOrient2TGraphMapConstIter
Definition at line 60 of file AsymCommon.h.
typedef TgtOrient2TGraphMap::iterator TgtOrient2TGraphMapIter
Definition at line 59 of file AsymCommon.h.
typedef std::map< ETargetOrient, ValErrPair > TgtOrient2ValErrMap
Definition at line 70 of file AsymCommon.h.
typedef TgtOrient2ValErrMap::const_iterator TgtOrient2ValErrMapConstIter
Definition at line 72 of file AsymCommon.h.
typedef TgtOrient2ValErrMap::iterator TgtOrient2ValErrMapIter
Definition at line 71 of file AsymCommon.h.
Enumeration Type Documentation
enum EAsymType
Enumerator
kPHYS_ASYM
kGEOM_ASYM
kLUMI_ASYM
Definition at line 33 of file AsymCommon.h.
enum EBeamEnergy
Enumerator
kINJECTION
kBEAM_ENERGY_100
kBEAM_ENERGY_250
kBEAM_ENERGY_255
Definition at line 31 of file AsymCommon.h.
enum EBeamId
Enumerator
kBLUE_BEAM
kYELLOW_BEAM
kUNKNOWN_BEAM
Definition at line 27 of file AsymCommon.h.
enum EFillType
Enumerator
kFILLTYPE_UNKNOWN
kFILLTYPE_PHYSICS
Definition at line 34 of file AsymCommon.h.
enum EPolarimeterId
Enumerator
kB1U
kY1D
kB2D
kY2U
kUNKNOWN_POLID
kHJET
Definition at line 26 of file AsymCommon.h.
enum ERingId
Enumerator
kBLUE_RING
kYELLOW_RING
kUNKNOWN_RING
Definition at line 28 of file AsymCommon.h.
enum ESpinState
Enumerator
kSPIN_DOWN
kSPIN_NULL
kSPIN_UP
Definition at line 32 of file AsymCommon.h.
enum EStreamId
Enumerator
kUPSTREAM
kDOWNSTREAM
kUNKNOWN_STREAM
Definition at line 29 of file AsymCommon.h.
enum ETargetOrient
Enumerator
kTARGET_H
kTARGET_V
kUNKNOWN_ORIENT
Definition at line 30 of file AsymCommon.h.
Function Documentation
TGraphErrors* AsymmetryGraph (int Mode, int N, float * x, float * y, float * ex, float * ey)
Definition at line 402 of file AsymCommon.cxx.
Referenced by AsymCalculator::CalcBunchAsym(), InvariantMassCorrelation(), AsymCalculator::ScanSinPhiFit(), AsymCalculator::SinPhiFit(), and TshiftFinder().
void binary_zero (int n, int mb)
Definition at line 385 of file AsymCommon.cxx.
Referenced by AsymCalculator::PrintWarning().
void DrawHorizLine (TH1 * h, float x1, float x2, float y, int color, int lstyle, int lwidth)
Definition at line 368 of file AsymCommon.cxx.
Referenced by BunchAsymmetryGaussianFit(), AsymCalculator::CalcBunchAsym(), AsymCalculator::DrawPlotvsTar(), HotBunchFinder(), InvariantMassCorrelation(), CnipolRunHists::PostFill(), AsymCalculator::ScanSinPhiFit(), AsymCalculator::SinPhiFit(), and StripAnomalyDetector().
void DrawLine (TH1 * h, float x1, float y1, float x2, float y2, int color, int lstyle, int lwidth)
Definition at line 357 of file AsymCommon.cxx.
Referenced by DrawHorizLine(), and DrawVertLine().
void DrawText (TH1 * h, float x, float y, int color, char * text)
Definition at line 345 of file AsymCommon.cxx.
Referenced by StripAnomalyDetector().
void DrawVertLine (TH1 * h, float x, float y, int color, int lwidth)
Definition at line 375 of file AsymCommon.cxx.
Referenced by CompleteHistogram(), and HotBunchFinder().
float GetMax (int N, float A[])
Definition at line 301 of file AsymCommon.cxx.
Referenced by GetMinMax(), and CnipolTargetHists::PostFill().
float GetMin (int N, float A[])
Definition at line 310 of file AsymCommon.cxx.
Referenced by GetMinMax().
void GetMinMax (int N, float A[], float margin, float & min, float & max)
Return Minimum and Maximum from array A[N].
If margin is not 0 the maximum is increased by max*margin and minimum is decreased by min*margin
Definition at line 324 of file AsymCommon.cxx.
Referenced by GetMinMaxOption(), CnipolTargetHists::PostFill(), and TshiftFinder().
void GetMinMaxOption (float prefix, int N, float A[], float margin, float & min, float & max)
Definition at line 336 of file AsymCommon.cxx.
Referenced by AsymCalculator::CalcBunchAsym(), InvariantMassCorrelation(), CnipolRunHists::PostFill(), AsymCalculator::ScanSinPhiFit(), AsymCalculator::SinPhiFit(), and TshiftFinder().
void hfith_ (int * , char * , char * , int * , float * , float * , float * , float * , float * , float * , int , int)
void hfithn_ (int * , char * , char * , int * , float * , float * , float * , float * , float * , float * , int , int)
void hhbook1d_ (int * , char * , int * , float * , float * , int)
void hhbook2d_ (int * , char * , int * , float * , float * , int * , float * , float * , int)
void hhf1_ (int * , float * , float *)
void hhf2_ (int * , float * , float * , float *)
void hhlimit_ (int *)
float hhmax_ (int *)
void hhpak_ (int * , float *)
void hhpake_ (int * , float *)
void hhrammar_ (float * , int *)
void hhrebin_ (int * , float * , float * , float * , float * , int * , int * , int *)
void hhrend_ (char * , int)
void hhropen_ (int * , char * , char * , char * , int * , int * , int , int , int)
void hhrout_ (int * , int * , char * , int)
float hhstati_ (int * , int * , char * , int * , int)
template<class Key , class T > std::string MapAsPhpArray (const std::map< Key, T > & m)
Definition at line 469 of file AsymCommon.h.
std::ostream& operator<< (std::ostream & os, const TgtOrient2ValErrMap & vep)
std::string PairAsPhpArray (const ValErrPair & p)
Definition at line 455 of file AsymCommon.cxx.
Referenced by AnaFillResult::Print(), and AnaMeasResult::PrintAsPhp().
void ReadRampTiming (char * filename)
Definition at line 418 of file AsymCommon.cxx.
template<class T > std::string SetAsPhpArray (const std::set< T > & s)
Definition at line 448 of file AsymCommon.h.
template<class T > std::string VecAsPhpArray (const std::vector< T > & v)
Definition at line 427 of file AsymCommon.h.