cnipol: /direct/eic+u/dsmirnov/cnipol/inc/AsymDbFile.h File Reference
AsymDbFile.h File Reference
#include <errno.h>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <string>
#include "rhicpol.h"
#include "rpoldata.h"
#include "AsymHeader.h"
#include "AsymDb.h"
#include "AsymGlobals.h"
#include "DbEntry.h"
Classes
class AsymDbFile
Deprecated class to select information about run periods from an ascii file.
Typedefs
typedef std::set< DbEntry > DbRunSet
typedef std::map< UShort_t,
DbEntry * > DbCommonRunMap
Functions
void readdb (double RUNID)
std::string GetVariables (std::string str)
void SetDefault ()
int ContinueScan (double ThisRunID, double RunID)
int MatchPolarimetry (double ThisRunID, double RefRunID)
void PrintRunDB ()
void StripHandler (int, int)
int FindDisableStrip ()
void BunchHandler (int, int)
int FindDisableBunch ()
Typedef Documentation
typedef std::map<UShort_t, DbEntry*> DbCommonRunMap
Definition at line 21 of file AsymDbFile.h.
typedef std::set<DbEntry> DbRunSet
Definition at line 20 of file AsymDbFile.h.
Function Documentation
void BunchHandler (int , int)
Definition at line 615 of file AsymDbFile.cxx.
Referenced by readdb().
int ContinueScan (double ThisRunID, double RunID)
Definition at line 671 of file AsymDbFile.cxx.
int FindDisableBunch ()
Definition at line 628 of file AsymDbFile.cxx.
int FindDisableStrip ()
Definition at line 598 of file AsymDbFile.cxx.
std::string GetVariables (std::string str)
int MatchPolarimetry (double ThisRunID, double RefRunID)
Definition at line 646 of file AsymDbFile.cxx.
Referenced by readdb().
void PrintRunDB ()
Definition at line 700 of file AsymDbFile.cxx.
Referenced by readdb().
void readdb (double RUNID)
Definition at line 395 of file AsymDbFile.cxx.
Referenced by getPreviousRun(), and main().
void SetDefault ()
Definition at line 572 of file AsymDbFile.cxx.
Referenced by readdb().
void StripHandler (int , int)
Definition at line 560 of file AsymDbFile.cxx.
Referenced by readdb().