cnipol: /direct/eic+u/dsmirnov/cnipol/inc/AsymPlot.h File Reference
AsymPlot.h File Reference
#include <cstdlib>
#include <math.h>
#include <iostream>
#include <fstream>
#include <string>
#include "TFile.h"
#include "TCanvas.h"
#include "TColor.h"
#include "TH1F.h"
#include "TH2F.h"
#include "TPostScript.h"
#include "TROOT.h"
#include "TStyle.h"
#include "TSystem.h"
#include "rhicpol.h"
#include "rpoldata.h"
#include "AsymCommon.h"
Classes
class AsymPlot
Functions
Int_t FileNotOK (Char_t file[])
18 Oct, 2010 - Dmitri Smirnov
Reorganized the file structure.
Int_t Usage (char *argv[])
Int_t Example (char *argv[])
void ColorSkime ()
Int_t IsOK (const Char_t histname[])
Variables
ofstream logfile
Function Documentation
void ColorSkime ()
Definition at line 54 of file AsymPlot.C.
Referenced by AsymPlot::PlotRaw().
Int_t Example (char * argv[])
Definition at line 43 of file AsymPlot.C.
Int_t FileNotOK (Char_t file[])
18 Oct, 2010 - Dmitri Smirnov
Reorganized the file structure.
Moved all definitions into the header file
Definition at line 13 of file AsymPlot.C.
Referenced by AsymPlot::FindRootFile(), and FindRootFile().
Int_t IsOK (const Char_t histname[])
Definition at line 77 of file AsymPlot.C.
Referenced by AsymPlot::PlotBanana(), PlotBanana(), AsymPlot::PlotErrorDetector(), AsymPlot::PlotFeedbackStrip(), PlotFeedbackStrip(), AsymPlot::PlotInvariantMass(), PlotInvariantMass(), AsymPlot::PlotMassEnergyCorrelation(), PlotMassEnergyCorrelation(), AsymPlot::PlotStrip(), and PlotStrip().
Int_t Usage (char * argv[])
Definition at line 21 of file AsymPlot.C.
Variable Documentation
ofstream logfile
Referenced by IsOK(), and main().