cnipol: /direct/eic+u/dsmirnov/cnipol/inc/AsymCalculator.h File Reference
AsymCalculator.h File Reference
#include <string>
#include "TGraphErrors.h"
#include "TH1.h"
#include "TH1D.h"
#include "DrawObjContainer.h"
#include "AsymGlobals.h"
#include "AsymErrorDetector.h"
Classes
class AsymCalculator
Functions
void CompleteHistogram ()
void FillAsymmetryHistgram (std::string mode, int sign, float *A, float *dA)
void calcBunchAsymmetryAverage ()
void calcLRAsymmetry (float X90[2], float X45[2], float &A, float &dA)
float TshiftFinder (int, int)
float ProfileError (float x)
Function Documentation
void calcBunchAsymmetryAverage ()
Definition at line 1457 of file AsymCalculator.cxx.
Referenced by AsymCalculator::CalcBunchAsym().
void calcLRAsymmetry (float X90[2], float X45[2], float & A, float & dA)
Definition at line 1513 of file AsymCalculator.cxx.
Referenced by calcBunchAsymmetryAverage().
void CompleteHistogram ()
Definition at line 49 of file AsymCalculator.cxx.
void FillAsymmetryHistgram (std::string mode, int sign, float * A, float * dA)
float ProfileError (float x)
Definition at line 957 of file AsymCalculator.cxx.
Referenced by AsymCalculator::CalcStatistics().
float TshiftFinder (int , int)
Definition at line 1014 of file AsymCalculator.cxx.