cnipol: /direct/eic+u/dsmirnov/cnipol/src/AsymErrorDetector.cxx File Reference
AsymErrorDetector.cxx File Reference
#include "AsymErrorDetector.h"
#include "TText.h"
#include "TF1.h"
#include "AsymAnaInfo.h"
#include "AnaMeasResult.h"
#include "MeasInfo.h"
#include "utils/utils.h"
Functions
void DetectorAnomaly ()
(Deprecated) Fit the slope of energy spectrum given in (-t) with exponential.
void InvariantMassCorrelation (int st)
void BananaFit (int st)
void StripAnomalyDetector ()
float BunchAsymmetryGaussianFit (TH1F *h1, TH2F *h2, float A[], float dA[], int err_code)
void BunchAsymmetryAnomaly ()
void BunchAnomalyDetector ()
void HotBunchFinder (int err_code)
void RegisterAnomaly (float x[], int nx, int y[], int ny, int z[], int &nz)
void RegisterAnomaly (int x[], int nx, int y[], int ny, int z[], int &nz)
void UnrecognizedAnomaly (int x[], int nx, int y[], int ny, int z[], int &nz)
Function Documentation
void BananaFit (int st)
Definition at line 131 of file AsymErrorDetector.cxx.
void BunchAnomalyDetector ()
Definition at line 466 of file AsymErrorDetector.cxx.
void BunchAsymmetryAnomaly ()
Definition at line 444 of file AsymErrorDetector.cxx.
Referenced by BunchAnomalyDetector().
float BunchAsymmetryGaussianFit (TH1F * h1, TH2F * h2, float A[], float dA[], int err_code)
Definition at line 328 of file AsymErrorDetector.cxx.
Referenced by BunchAsymmetryAnomaly().
void DetectorAnomaly ()
(Deprecated) Fit the slope of energy spectrum given in (-t) with exponential.
24 Dec, 2010 - Dmitri Smirnov
Heavily modified and cleaned up.
Definition at line 27 of file AsymErrorDetector.cxx.
void HotBunchFinder (int err_code)
Definition at line 491 of file AsymErrorDetector.cxx.
Referenced by BunchAnomalyDetector().
void InvariantMassCorrelation (int st)
Definition at line 62 of file AsymErrorDetector.cxx.
Referenced by StripAnomalyDetector().
void RegisterAnomaly (int x[], int nx, int y[], int ny, int z[], int & nz)
Definition at line 600 of file AsymErrorDetector.cxx.
void RegisterAnomaly (float x[], int nx, int y[], int ny, int z[], int & nz)
Definition at line 588 of file AsymErrorDetector.cxx.
Referenced by BunchAsymmetryGaussianFit(), and RegisterAnomaly().
void StripAnomalyDetector ()
Definition at line 170 of file AsymErrorDetector.cxx.
Referenced by TshiftFinder().
void UnrecognizedAnomaly (int x[], int nx, int y[], int ny, int z[], int & nz)
Definition at line 636 of file AsymErrorDetector.cxx.