cnipol: src/AsymPlot.C File Reference
AsymPlot.C File Reference
#include "AsymPlot.h"
Functions
Int_t FileNotOK (Char_t file[])
18 Oct, 2010 - Dmitri Smirnov
Int_t Usage (char *argv[])
Int_t Example (char *argv[])
void ColorSkime ()
Int_t IsOK (Char_t histname[])
Int_t PlotStrip (TFile *rootfile, TCanvas *CurC, TPostScript *ps, Int_t stID)
Int_t PlotBanana (TFile *rootfile, TCanvas *CurC, TPostScript *ps)
Int_t PlotMassEnergyCorrelation (TFile *rootfile, TCanvas *CurC, TPostScript *ps)
Int_t PlotInvariantMass (TFile *rootfile, TCanvas *CurC, TPostScript *ps)
Int_t PlotStrip (TFile *rootfile, TCanvas *CurC, TPostScript *ps)
Int_t PlotFeedbackStrip (TFile *rootfile, TCanvas *CurC, TPostScript *ps)
void FindRootFile ()
int main (int argc, char **argv)
Function Documentation
void ColorSkime ()
Definition at line 54 of file AsymPlot.C.
Referenced by AsymPlot::PlotRaw().
Int_t Example (char * argv[])
Definition at line 43 of file AsymPlot.C.
Referenced by main().
Int_t FileNotOK (Char_t file[])
18 Oct, 2010 - Dmitri Smirnov
Reorganized the file structure. Moved all definitions into the header file
Definition at line 13 of file AsymPlot.C.
Referenced by AsymPlot::FindRootFile(), and FindRootFile().
void FindRootFile ()
Definition at line 452 of file AsymPlot.C.
Referenced by main().
Int_t IsOK (Char_t histname[])
Definition at line 77 of file AsymPlot.C.
Referenced by AsymPlot::PlotBanana(), PlotBanana(), AsymPlot::PlotErrorDetector(), AsymPlot::PlotFeedbackStrip(), PlotFeedbackStrip(), AsymPlot::PlotInvariantMass(), PlotInvariantMass(), AsymPlot::PlotMassEnergyCorrelation(), PlotMassEnergyCorrelation(), AsymPlot::PlotStrip(), and PlotStrip().
int main (int argc, char ** argv)
Definition at line 485 of file AsymPlot.C.
Int_t PlotBanana (TFile * rootfile, TCanvas * CurC, TPostScript * ps)
Definition at line 119 of file AsymPlot.C.
Referenced by AsymPlot::PlotStrip(), and PlotStrip().
Int_t PlotFeedbackStrip (TFile * rootfile, TCanvas * CurC, TPostScript * ps)
Definition at line 228 of file AsymPlot.C.
Int_t PlotInvariantMass (TFile * rootfile, TCanvas * CurC, TPostScript * ps)
Definition at line 181 of file AsymPlot.C.
Referenced by AsymPlot::PlotStrip(), and PlotStrip().
Int_t PlotMassEnergyCorrelation (TFile * rootfile, TCanvas * CurC, TPostScript * ps)
Definition at line 149 of file AsymPlot.C.
Referenced by AsymPlot::PlotStrip(), and PlotStrip().
Int_t PlotStrip (TFile * rootfile, TCanvas * CurC, TPostScript * ps, Int_t stID)
Definition at line 86 of file AsymPlot.C.
Referenced by main().
Int_t PlotStrip (TFile * rootfile, TCanvas * CurC, TPostScript * ps)
Definition at line 215 of file AsymPlot.C.
Int_t Usage (char * argv[])
Definition at line 21 of file AsymPlot.C.
Referenced by main().