cnipol: BiasCurrentUtil Class Reference
BiasCurrentUtil Class Reference
#include <BiasCurrentUtil.h>
Static Public Member Functions
static std::string GetBiasCurrentLoggerName (EPolarimeterId polId)
static EPolarimeterId ParseLoggerPolId (const std::string &cell_name)
static std::vector< double > FillBiasCurrentMeanValue (opencdev::mean_result_t &bias_mean_value, EPolarimeterId polId)
Detailed Description
Definition at line 8 of file BiasCurrentUtil.h.
Member Function Documentation
vector< double > BiasCurrentUtil::FillBiasCurrentMeanValue (opencdev::mean_result_t & bias_mean_value, EPolarimeterId polId) [static]
Definition at line 52 of file BiasCurrentUtil.cxx.
Referenced by Calibrator::ApplyRun13BiasCurrentCorrection(), and FillBiasCurrent().
string BiasCurrentUtil::GetBiasCurrentLoggerName (EPolarimeterId polId) [static]
Definition at line 18 of file BiasCurrentUtil.cxx.
Referenced by Calibrator::ApplyRun13BiasCurrentCorrection(), and FillBiasCurrent().
EPolarimeterId BiasCurrentUtil::ParseLoggerPolId (const std::string & cell_name) [static]
Definition at line 32 of file BiasCurrentUtil.cxx.
Referenced by FillBiasCurrent(), and FillBiasCurrentMeanValue().
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/BiasCurrentUtil.h
/direct/eic+u/dsmirnov/cnipol/src/BiasCurrentUtil.cxx