cnipol: ChannelEvent Class Reference
ChannelEvent Class Reference
#include <ChannelEvent.h>
Public Member Functions
ChannelEvent ()
Default constructor.
~ChannelEvent ()
Default destructor.
void SetEventConfig (EventConfig *eventConfig)
void SetEventId (ChannelEventId &chEventId)
void SetChannelData (ChannelData &chData)
ChannelData GetChannelData () const
ChannelEventId GetEventId () const
UChar_t GetDetectorId () const
UInt_t GetRevolutionId () const
UChar_t GetChannelId () const
UChar_t GetChannelIndex () const
UChar_t GetBunchId () const
UShort_t GetDelimiterId () const
UChar_t GetAmpltd () const
UChar_t GetIntgrl () const
UChar_t GetTdc () const
UChar_t GetTdcAMax () const
Float_t GetEnergyA () const
Float_t GetKinEnergyA ()
Float_t GetKinEnergyAEDepend ()
Float_t GetKinEnergyAEDependAverage ()
Float_t GetKinEnergyAEstimate ()
Float_t GetKinEnergyADLCorrEstimate ()
Float_t GetKinEnergyAEstimateEDepend ()
Float_t GetFunnyEnergyA ()
Float_t GetEnergyI ()
Float_t GetTime () const
Float_t GetTime2 () const
Float_t GetTimeOfFlight ()
Float_t GetTimeOfFlight2 ()
Float_t GetTimeOfFlightEstimate ()
Float_t GetCarbonMass ()
Float_t GetCarbonMassEstimate ()
Float_t GetMandelstamT ()
Float_t GetTdcAdcTimeDiff ()
virtual void Print (const Option_t *opt="") const
Bool_t PassCutRawAlpha ()
Bool_t PassCutSiliconChannel ()
Returns true for silicon channels.
Bool_t PassCutDepEnergyTime ()
Bool_t PassCutKinEnergyAEDepend ()
Bool_t PassCutKinEnergyAEDependAverage ()
Bool_t PassCutKinEnergyADLCorrEstimate ()
Bool_t PassCutCarbonMass ()
Bool_t PassCutCarbonMassEstimate ()
Bool_t PassCutPulser ()
Bool_t PassCutNoise ()
Bool_t PassCutEnabledChannel ()
Bool_t PassCutTargetChannel ()
Bool_t PassCutPmtChannel () const
Bool_t PassCutHamaChannel ()
Bool_t PassCutPmtNoise ()
Bool_t PassCutEmptyBunch () const
Bool_t IsSpinFlipperMarkerChannel () const
Detailed Description
Definition at line 27 of file ChannelEvent.h.
Constructor & Destructor Documentation
ChannelEvent::ChannelEvent ()
Default constructor.
Definition at line 12 of file ChannelEvent.cxx.
ChannelEvent::~ChannelEvent ()
Default destructor.
Definition at line 19 of file ChannelEvent.cxx.
Member Function Documentation
UChar_t ChannelEvent::GetAmpltd () const [inline]
Definition at line 45 of file ChannelEvent.h.
Referenced by CnipolTargetHists::Fill(), CnipolRawHists::FillPassOne(), CnipolRawExtendedHists::FillPassOne(), CnipolPulserHists::FillPassOne(), CnipolPmtHists::FillPassOne(), PassCutNoise(), PassCutPmtNoise(), and PassCutPulser().
UChar_t ChannelEvent::GetBunchId () const [inline]
Definition at line 43 of file ChannelEvent.h.
Referenced by CnipolSpinStudyHists::Fill(), CnipolHists::Fill(), CnipolAsymHists::Fill(), CnipolRawHists::FillPassOne(), CnipolRawExtendedHists::FillPassOne(), CnipolPulserHists::FillPassOne(), and PassCutEmptyBunch().
Float_t ChannelEvent::GetCarbonMass ()
Definition at line 154 of file ChannelEvent.cxx.
Referenced by CnipolKinematHists::Fill(), CnipolKinemaCleanHists::Fill(), and PassCutCarbonMass().
Float_t ChannelEvent::GetCarbonMassEstimate ()
Definition at line 164 of file ChannelEvent.cxx.
Referenced by PassCutCarbonMassEstimate().
ChannelData ChannelEvent::GetChannelData () const [inline]
Definition at line 37 of file ChannelEvent.h.
Referenced by CnipolAlphaHists::FillPassOne().
UChar_t ChannelEvent::GetChannelId () const [inline]
Definition at line 41 of file ChannelEvent.h.
Referenced by CnipolTargetHists::Fill(), CnipolSpinStudyHists::Fill(), CnipolPulserHists::Fill(), CnipolProfileHists::Fill(), CnipolKinematHists::Fill(), CnipolKinemaCleanHists::Fill(), CnipolHists::Fill(), CnipolAsymHists::Fill(), CnipolRawHists::FillPassOne(), CnipolRawExtendedHists::FillPassOne(), CnipolPulserHists::FillPassOne(), CnipolPmtHists::FillPassOne(), CnipolAlphaHists::FillPassOne(), GetCarbonMass(), GetEnergyA(), GetKinEnergyA(), GetKinEnergyAEDepend(), GetTdcAdcTimeDiff(), GetTimeOfFlight(), GetTimeOfFlight2(), IsSpinFlipperMarkerChannel(), PassCutEnabledChannel(), PassCutHamaChannel(), PassCutPmtChannel(), PassCutSiliconChannel(), and PassCutTargetChannel().
UChar_t ChannelEvent::GetChannelIndex () const [inline]
Definition at line 42 of file ChannelEvent.h.
UShort_t ChannelEvent::GetDelimiterId () const [inline]
Definition at line 44 of file ChannelEvent.h.
Referenced by CnipolTargetHists::Fill().
UChar_t ChannelEvent::GetDetectorId () const [inline]
Definition at line 39 of file ChannelEvent.h.
Float_t ChannelEvent::GetEnergyA () const
Definition at line 25 of file ChannelEvent.cxx.
Referenced by CnipolHists::Fill(), CnipolPulserHists::FillPassOne(), GetFunnyEnergyA(), GetKinEnergyA(), GetKinEnergyADLCorrEstimate(), GetKinEnergyAEDepend(), GetKinEnergyAEDependAverage(), GetKinEnergyAEstimate(), GetKinEnergyAEstimateEDepend(), PassCutDepEnergyTime(), and Print().
Float_t ChannelEvent::GetEnergyI ()
Definition at line 101 of file ChannelEvent.cxx.
ChannelEventId ChannelEvent::GetEventId () const [inline]
Definition at line 38 of file ChannelEvent.h.
Referenced by std::less< ChannelEvent >::operator()().
Float_t ChannelEvent::GetFunnyEnergyA ()
Definition at line 92 of file ChannelEvent.cxx.
UChar_t ChannelEvent::GetIntgrl () const [inline]
Definition at line 46 of file ChannelEvent.h.
Referenced by CnipolRawHists::FillPassOne(), CnipolRawExtendedHists::FillPassOne(), CnipolPulserHists::FillPassOne(), and CnipolPmtHists::FillPassOne().
Float_t ChannelEvent::GetKinEnergyA ()
Definition at line 34 of file ChannelEvent.cxx.
Float_t ChannelEvent::GetKinEnergyADLCorrEstimate ()
Definition at line 72 of file ChannelEvent.cxx.
Referenced by PassCutKinEnergyADLCorrEstimate().
Float_t ChannelEvent::GetKinEnergyAEDepend ()
Definition at line 44 of file ChannelEvent.cxx.
Referenced by CnipolPulserHists::Fill(), CnipolHists::Fill(), CnipolAsymHists::Fill(), GetCarbonMass(), GetTdcAdcTimeDiff(), and PassCutKinEnergyAEDepend().
Float_t ChannelEvent::GetKinEnergyAEDependAverage ()
Definition at line 54 of file ChannelEvent.cxx.
Referenced by PassCutKinEnergyAEDependAverage().
Float_t ChannelEvent::GetKinEnergyAEstimate ()
Definition at line 63 of file ChannelEvent.cxx.
Referenced by GetCarbonMassEstimate(), and GetMandelstamT().
Float_t ChannelEvent::GetKinEnergyAEstimateEDepend ()
Definition at line 83 of file ChannelEvent.cxx.
Float_t ChannelEvent::GetMandelstamT ()
Definition at line 174 of file ChannelEvent.cxx.
UInt_t ChannelEvent::GetRevolutionId () const [inline]
Definition at line 40 of file ChannelEvent.h.
Referenced by AsymRoot::AddSpinFlipperMarker(), CnipolTargetHists::Fill(), CnipolSpinStudyHists::Fill(), CnipolProfileHists::Fill(), CnipolHists::Fill(), CnipolAsymHists::Fill(), CnipolRawHists::FillPassOne(), CnipolRawExtendedHists::FillPassOne(), and AsymRoot::UpdateFromChannelEvent().
UChar_t ChannelEvent::GetTdc () const [inline]
Definition at line 47 of file ChannelEvent.h.
Referenced by CnipolRawHists::FillPassOne(), CnipolRawExtendedHists::FillPassOne(), CnipolPulserHists::FillPassOne(), CnipolPmtHists::FillPassOne(), PassCutNoise(), and PassCutPulser().
Float_t ChannelEvent::GetTdcAdcTimeDiff ()
Definition at line 181 of file ChannelEvent.cxx.
Referenced by CnipolHists::Fill().
UChar_t ChannelEvent::GetTdcAMax () const [inline]
Definition at line 48 of file ChannelEvent.h.
Float_t ChannelEvent::GetTime () const
Definition at line 111 of file ChannelEvent.cxx.
Referenced by CnipolHists::Fill(), CnipolPulserHists::FillPassOne(), GetTimeOfFlight(), GetTimeOfFlightEstimate(), and Print().
Float_t ChannelEvent::GetTime2 () const
Definition at line 118 of file ChannelEvent.cxx.
Referenced by GetTimeOfFlight2().
Float_t ChannelEvent::GetTimeOfFlight ()
Definition at line 125 of file ChannelEvent.cxx.
Referenced by CnipolPulserHists::Fill(), CnipolHists::Fill(), and GetCarbonMass().
Float_t ChannelEvent::GetTimeOfFlight2 ()
Definition at line 135 of file ChannelEvent.cxx.
Referenced by GetTdcAdcTimeDiff().
Float_t ChannelEvent::GetTimeOfFlightEstimate ()
Definition at line 145 of file ChannelEvent.cxx.
Referenced by GetCarbonMassEstimate().
Bool_t ChannelEvent::IsSpinFlipperMarkerChannel () const
Definition at line 372 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutCarbonMass ()
Definition at line 285 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutCarbonMassEstimate ()
Definition at line 295 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutDepEnergyTime ()
Definition at line 225 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutEmptyBunch () const
Definition at line 406 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutEnabledChannel ()
Definition at line 340 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutHamaChannel ()
Definition at line 384 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutKinEnergyADLCorrEstimate ()
Definition at line 275 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutKinEnergyAEDepend ()
Definition at line 255 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutKinEnergyAEDependAverage ()
Definition at line 265 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutNoise ()
Definition at line 319 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutPmtChannel () const
Definition at line 360 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutPmtNoise ()
Definition at line 396 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutPulser ()
Definition at line 305 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutRawAlpha ()
Definition at line 204 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutSiliconChannel ()
Returns true for silicon channels.
Definition at line 215 of file ChannelEvent.cxx.
Bool_t ChannelEvent::PassCutTargetChannel ()
Definition at line 347 of file ChannelEvent.cxx.
void ChannelEvent::Print (const Option_t * opt = "") const [virtual]
Definition at line 191 of file ChannelEvent.cxx.
Referenced by AsymRoot::PrintChannelEvent().
void ChannelEvent::SetChannelData (ChannelData & chData) [inline]
Definition at line 36 of file ChannelEvent.h.
Referenced by AsymRoot::SetChannelEvent().
void ChannelEvent::SetEventConfig (EventConfig * eventConfig) [inline]
Definition at line 34 of file ChannelEvent.h.
Referenced by AsymRoot::AsymRoot().
void ChannelEvent::SetEventId (ChannelEventId & chEventId) [inline]
Definition at line 35 of file ChannelEvent.h.
Referenced by AsymRoot::SetChannelEvent().
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/ChannelEvent.h
/direct/eic+u/dsmirnov/cnipol/src/ChannelEvent.cxx