cnipol: MAsymRoot Class Reference
MAsymRoot Class Reference
#include <MAsymRoot.h>
Public Member Functions
MAsymRoot ()
MAsymRoot (MAsymAnaInfo &anaInfo)
~MAsymRoot ()
void SetHists (DrawObjContainer &hists)
void SetAnaGlobResult (AnaGlobResult *agr)
void SaveAs (std::string pattern, std::string dir)
void UpdMinMax (EventConfig &mm)
void UpdMinMaxFill (UInt_t fillId)
void UpdMinMaxTime (time_t time)
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
Protected Attributes
AnaInfo * fAnaInfo
DrawObjContainer * fHists
AnaGlobResult * fAnaGlobResult
Float_t fMinFill
Float_t fMaxFill
time_t fMinTime
time_t fMaxTime
FILE * fFilePhp
Detailed Description
Definition at line 16 of file MAsymRoot.h.
Constructor & Destructor Documentation
MAsymRoot::MAsymRoot ()
Definition at line 16 of file MAsymRoot.cxx.
MAsymRoot::MAsymRoot (MAsymAnaInfo & anaInfo)
Definition at line 27 of file MAsymRoot.cxx.
MAsymRoot::~MAsymRoot ()
Definition at line 40 of file MAsymRoot.cxx.
Member Function Documentation
void MAsymRoot::Print (const Option_t * opt = "") const
Definition at line 103 of file MAsymRoot.cxx.
Referenced by main().
void MAsymRoot::PrintAsPhp (FILE * f = stdout) const
Definition at line 111 of file MAsymRoot.cxx.
Referenced by Print().
void MAsymRoot::SaveAs (std::string pattern, std::string dir)
Definition at line 58 of file MAsymRoot.cxx.
Referenced by main().
void MAsymRoot::SetAnaGlobResult (AnaGlobResult * agr)
Definition at line 51 of file MAsymRoot.cxx.
Referenced by main().
void MAsymRoot::SetHists (DrawObjContainer & hists)
Definition at line 44 of file MAsymRoot.cxx.
Referenced by main().
void MAsymRoot::UpdMinMax (EventConfig & mm)
Definition at line 79 of file MAsymRoot.cxx.
Referenced by main().
void MAsymRoot::UpdMinMaxFill (UInt_t fillId)
Definition at line 87 of file MAsymRoot.cxx.
Referenced by UpdMinMax().
void MAsymRoot::UpdMinMaxTime (time_t time)
Definition at line 95 of file MAsymRoot.cxx.
Referenced by UpdMinMax().
Member Data Documentation
AnaGlobResult* MAsymRoot::fAnaGlobResult protected
Definition at line 22 of file MAsymRoot.h.
Referenced by PrintAsPhp(), and SetAnaGlobResult().
AnaInfo* MAsymRoot::fAnaInfo protected
Definition at line 20 of file MAsymRoot.h.
Referenced by SaveAs().
FILE* MAsymRoot::fFilePhp protected
Definition at line 27 of file MAsymRoot.h.
Referenced by Print().
DrawObjContainer* MAsymRoot::fHists protected
Definition at line 21 of file MAsymRoot.h.
Referenced by SaveAs(), and SetHists().
Float_t MAsymRoot::fMaxFill protected
Definition at line 24 of file MAsymRoot.h.
Referenced by SaveAs(), and UpdMinMaxFill().
time_t MAsymRoot::fMaxTime protected
Definition at line 26 of file MAsymRoot.h.
Referenced by UpdMinMaxTime().
Float_t MAsymRoot::fMinFill protected
Definition at line 23 of file MAsymRoot.h.
Referenced by SaveAs(), and UpdMinMaxFill().
time_t MAsymRoot::fMinTime protected
Definition at line 25 of file MAsymRoot.h.
Referenced by UpdMinMaxTime().
The documentation for this class was generated from the following files:
inc/MAsymRoot.h
src/MAsymRoot.cxx