cnipol: MAlphaAnaInfo Class Reference
MAlphaAnaInfo Class Reference
This class takes care of the command line options specific to the 'malpha' executable.
#include <MAlphaAnaInfo.h>
Public Types
enum Option { OPTION_MLIST = 0x20000001, OPTION_OFILE = 0x20000002 }
Public Types inherited from AnaInfo
enum Flag {
FLAG_COPY = 0x10000400, FLAG_READ_FROM_DB = 0x10000100, FLAG_UPDATE_DB = 0x10000200, FLAG_NO_UPDATE_DB = 0x90000200,
FLAG_USE_DB = 0x10000300, FLAG_CREATE_THUMBS = 0x10000800
}
enum Option {
OPTION_POL_ID = 0x20004000, OPTION_SET_CALIB_ALPHA = 0x20001000, OPTION_DET_DISABLE = 0x20000001, OPTION_SUFFIX = 0x20000002,
OPTION_ALPHA_SOURCES = 0x20000003
}
enum Mode { MODE_GRAPH = 0x02000000, MODE_NO_GRAPH = 0x82000000 }
Public Member Functions
MAlphaAnaInfo ()
void SetMListFileName (std::string listName)
std::string GetMListFileName ()
std::string GetMListFullPath ()
std::string GetExternInfoPath ()
void ProcessOptions (int argc, char **argv)
void VerifyOptions ()
virtual void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
void PrintUsage ()
Public Member Functions inherited from AnaInfo
AnaInfo ()
~AnaInfo ()
std::string GetSuffix () const
std::string GetResultsDir () const
std::string GetOutDir () const
std::string GetSlowControlLogDir () const
std::string GetImageDir () const
virtual std::string GetAnaInfoFileName () const
std::string GetStdLogFileName () const
std::string GetRootFileName () const
FILE * GetAnaInfoFile () const
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
virtual void CopyResults ()
Bool_t HasGraphBit () const
Public Attributes
std::string fMListFileName
std::string fOutputFileName
Public Attributes inherited from AnaInfo
std::string fAsymVersion
std::string fSuffix
ULong_t fModes
time_t fAnaDateTime
Double_t fAnaTimeReal
Double_t fAnaTimeCpu
Str2StrMap fAsymEnv
FILE * fFileMeasInfo
FILE * fFileStdLog
std::string fFileStdLogName
Bool_t fFlagCopyResults
Bool_t fFlagUseDb
Bool_t fFlagUpdateDb
Bool_t fFlagCreateThumbs
UserGroup_t fUserGroup
Short_t fAlphaSourceCount
Additional Inherited Members
Protected Member Functions inherited from AnaInfo
void Init ()
void MakeOutDir ()
Protected Attributes inherited from AnaInfo
std::string fOutputName
Detailed Description
This class takes care of the command line options specific to the 'malpha' executable.
The common options are taken care of by the AnaInfo class.
Definition at line 16 of file MAlphaAnaInfo.h.
Member Enumeration Documentation
enum MAlphaAnaInfo::Option
Enumerator
OPTION_MLIST
OPTION_OFILE
Definition at line 20 of file MAlphaAnaInfo.h.
Constructor & Destructor Documentation
MAlphaAnaInfo::MAlphaAnaInfo ()
Definition at line 16 of file MAlphaAnaInfo.cxx.
Member Function Documentation
string MAlphaAnaInfo::GetExternInfoPath ()
Definition at line 39 of file MAlphaAnaInfo.cxx.
string MAlphaAnaInfo::GetMListFileName ()
Definition at line 29 of file MAlphaAnaInfo.cxx.
Referenced by main().
string MAlphaAnaInfo::GetMListFullPath ()
Definition at line 34 of file MAlphaAnaInfo.cxx.
Referenced by main(), and VerifyOptions().
void MAlphaAnaInfo::Print (const Option_t * opt = "") const virtual
Definition at line 127 of file MAlphaAnaInfo.cxx.
void MAlphaAnaInfo::PrintAsPhp (FILE * f = stdout) const
Definition at line 135 of file MAlphaAnaInfo.cxx.
Referenced by Print().
void MAlphaAnaInfo::PrintUsage () virtual
Reimplemented from AnaInfo.
Definition at line 144 of file MAlphaAnaInfo.cxx.
Referenced by ProcessOptions(), and VerifyOptions().
void MAlphaAnaInfo::ProcessOptions (int argc, char ** argv) virtual
Reimplemented from AnaInfo.
Definition at line 46 of file MAlphaAnaInfo.cxx.
Referenced by main().
void MAlphaAnaInfo::SetMListFileName (std::string listName)
Definition at line 24 of file MAlphaAnaInfo.cxx.
Referenced by ProcessOptions().
void MAlphaAnaInfo::VerifyOptions () virtual
Reimplemented from AnaInfo.
Definition at line 98 of file MAlphaAnaInfo.cxx.
Referenced by main().
Member Data Documentation
std::string MAlphaAnaInfo::fMListFileName
Definition at line 26 of file MAlphaAnaInfo.h.
Referenced by GetMListFileName(), GetMListFullPath(), PrintAsPhp(), SetMListFileName(), and VerifyOptions().
std::string MAlphaAnaInfo::fOutputFileName
Definition at line 30 of file MAlphaAnaInfo.h.
Referenced by main(), ProcessOptions(), and VerifyOptions().
The documentation for this class was generated from the following files:
inc/MAlphaAnaInfo.h
src/MAlphaAnaInfo.cxx