cnipol: AnaInfo Class Reference
AnaInfo Class Reference
#include <AnaInfo.h>
Public Types
enum Flag {
FLAG_COPY = 0x10000400, FLAG_READ_FROM_DB = 0x10000100, FLAG_UPDATE_DB = 0x10000200, FLAG_NO_UPDATE_DB = 0x90000200,
FLAG_USE_DB = 0x10000300, FLAG_CREATE_THUMBS = 0x10000800
}
enum Option {
OPTION_POL_ID = 0x20004000, OPTION_SET_CALIB_ALPHA = 0x20001000, OPTION_DET_DISABLE = 0x20000001, OPTION_SUFFIX = 0x20000002,
OPTION_ALPHA_SOURCES = 0x20000003
}
enum Mode { MODE_GRAPH = 0x02000000, MODE_NO_GRAPH = 0x82000000 }
Public Member Functions
AnaInfo ()
~AnaInfo ()
std::string GetSuffix () const
std::string GetResultsDir () const
std::string GetOutDir () const
std::string GetSlowControlLogDir () const
std::string GetImageDir () const
virtual std::string GetAnaInfoFileName () const
std::string GetStdLogFileName () const
std::string GetRootFileName () const
FILE * GetAnaInfoFile () const
virtual void ProcessOptions (int argc, char **argv)
virtual void VerifyOptions ()
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
virtual void PrintUsage ()
virtual void CopyResults ()
Bool_t HasGraphBit () const
Public Attributes
std::string fAsymVersion
std::string fSuffix
Additional unique identifier for analysis job.
ULong_t fModes
time_t fAnaDateTime
Date/time when data analysis started.
Double_t fAnaTimeReal
Time in seconds to process input raw file.
Double_t fAnaTimeCpu
Time in seconds to process input raw file.
Str2StrMap fAsymEnv
FILE * fFileMeasInfo
FILE * fFileStdLog
std::string fFileStdLogName
Bool_t fFlagCopyResults
Bool_t fFlagUseDb
Bool_t fFlagUpdateDb
Bool_t fFlagCreateThumbs
UserGroup_t fUserGroup
Short_t fAlphaSourceCount
Protected Member Functions
void Init ()
void MakeOutDir ()
Protected Attributes
std::string fOutputName
Detailed Description
Definition at line 16 of file AnaInfo.h.
Member Enumeration Documentation
enum AnaInfo::Flag
Enumerator:
FLAG_COPY
FLAG_READ_FROM_DB
FLAG_UPDATE_DB
FLAG_NO_UPDATE_DB
FLAG_USE_DB
FLAG_CREATE_THUMBS
Definition at line 21 of file AnaInfo.h.
enum AnaInfo::Mode
Enumerator:
MODE_GRAPH
MODE_NO_GRAPH
Reimplemented in AsymAnaInfo.
Definition at line 35 of file AnaInfo.h.
enum AnaInfo::Option
Enumerator:
OPTION_POL_ID
OPTION_SET_CALIB_ALPHA
OPTION_DET_DISABLE
OPTION_SUFFIX
OPTION_ALPHA_SOURCES
Reimplemented in AsymAnaInfo, MAlphaAnaInfo, and MAsymAnaInfo.
Definition at line 28 of file AnaInfo.h.
Constructor & Destructor Documentation
AnaInfo::AnaInfo ()
Definition at line 21 of file AnaInfo.cxx.
AnaInfo::~AnaInfo ()
Definition at line 41 of file AnaInfo.cxx.
Member Function Documentation
void AnaInfo::CopyResults () [virtual]
Definition at line 205 of file AnaInfo.cxx.
Referenced by main().
FILE * AnaInfo::GetAnaInfoFile () const
Definition at line 106 of file AnaInfo.cxx.
Referenced by main().
string AnaInfo::GetAnaInfoFileName () const [virtual]
Reimplemented in AsymAnaInfo.
Definition at line 103 of file AnaInfo.cxx.
Referenced by VerifyOptions().
string AnaInfo::GetImageDir () const
Definition at line 102 of file AnaInfo.cxx.
Referenced by main().
string AnaInfo::GetOutDir () const
Definition at line 118 of file AnaInfo.cxx.
Referenced by CopyResults(), AsymAnaInfo::GetAnaInfoFileName(), GetAnaInfoFileName(), GetImageDir(), GetRootFileName(), AsymAnaInfo::GetRootTreeFileName(), AsymAnaInfo::GetRunConfFileName(), GetStdLogFileName(), and MakeOutDir().
string AnaInfo::GetResultsDir () const
Definition at line 111 of file AnaInfo.cxx.
Referenced by MAsymAnaInfo::GetExternInfoPath(), MAlphaAnaInfo::GetExternInfoPath(), MAsymAnaInfo::GetMListFullPath(), MAlphaAnaInfo::GetMListFullPath(), main(), MAsymAnaInfo::VerifyOptions(), and MAlphaAnaInfo::VerifyOptions().
string AnaInfo::GetRootFileName () const
Definition at line 105 of file AnaInfo.cxx.
Referenced by main().
std::string AnaInfo::GetSlowControlLogDir () const
Definition at line 124 of file AnaInfo.cxx.
Referenced by Calibrator::ApplyRun13BiasCurrentCorrection(), and main().
string AnaInfo::GetStdLogFileName () const
Definition at line 104 of file AnaInfo.cxx.
Referenced by VerifyOptions().
string AnaInfo::GetSuffix () const
Definition at line 101 of file AnaInfo.cxx.
Referenced by AsymAnaInfo::GetAlphaCalibRun(), AsymAnaInfo::GetAnaInfoFileName(), GetAnaInfoFileName(), GetImageDir(), GetRootFileName(), AsymAnaInfo::GetRootTreeFileName(), AsymAnaInfo::GetRunConfFileName(), GetStdLogFileName(), and main().
Bool_t AnaInfo::HasGraphBit () const
Definition at line 108 of file AnaInfo.cxx.
Referenced by main().
void AnaInfo::Init () [protected]
Definition at line 49 of file AnaInfo.cxx.
void AnaInfo::MakeOutDir () [protected]
Definition at line 78 of file AnaInfo.cxx.
Referenced by VerifyOptions().
void AnaInfo::Print (const Option_t * opt = "") const
Reimplemented in AsymAnaInfo, MAlphaAnaInfo, and MAsymAnaInfo.
Definition at line 162 of file AnaInfo.cxx.
void AnaInfo::PrintAsPhp (FILE * f = stdout) const
Reimplemented in AsymAnaInfo, MAlphaAnaInfo, and MAsymAnaInfo.
Definition at line 170 of file AnaInfo.cxx.
Referenced by Print().
void AnaInfo::PrintUsage () [virtual]
Reimplemented in AsymAnaInfo, MAlphaAnaInfo, and MAsymAnaInfo.
Definition at line 222 of file AnaInfo.cxx.
Referenced by VerifyOptions().
void AnaInfo::ProcessOptions (int argc, char ** argv) [virtual]
Reimplemented in AsymAnaInfo, MAlphaAnaInfo, and MAsymAnaInfo.
Definition at line 131 of file AnaInfo.cxx.
void AnaInfo::VerifyOptions () [virtual]
Reimplemented in AsymAnaInfo, MAlphaAnaInfo, and MAsymAnaInfo.
Definition at line 137 of file AnaInfo.cxx.
Member Data Documentation
Short_t AnaInfo::fAlphaSourceCount
Definition at line 58 of file AnaInfo.h.
Referenced by AsymAnaInfo::PrintAsPhp(), AsymAnaInfo::ProcessOptions(), and MeasInfo::Update().
time_t AnaInfo::fAnaDateTime
Date/time when data analysis started.
Definition at line 46 of file AnaInfo.h.
Referenced by EventConfig::GetSignature(), main(), and PrintAsPhp().
Double_t AnaInfo::fAnaTimeCpu
Time in seconds to process input raw file.
Definition at line 48 of file AnaInfo.h.
Referenced by PrintAsPhp().
Double_t AnaInfo::fAnaTimeReal
Time in seconds to process input raw file.
Definition at line 47 of file AnaInfo.h.
Referenced by EventConfig::GetSignature(), main(), and PrintAsPhp().
Str2StrMap AnaInfo::fAsymEnv
Definition at line 49 of file AnaInfo.h.
Referenced by AsymDbFile::AsymDbFile(), AsymAnaInfo::GetAlphaCalibFile(), GetOutDir(), AsymAnaInfo::GetRawDataFileName(), GetResultsDir(), GetSlowControlLogDir(), Init(), PrintAsPhp(), and AsymAnaInfo::VerifyOptions().
std::string AnaInfo::fAsymVersion
Definition at line 43 of file AnaInfo.h.
Referenced by EventConfig::GetSignature(), main(), PrintAsPhp(), and MAsymSingleFillHists::SetSignature().
FILE* AnaInfo::fFileMeasInfo
Definition at line 50 of file AnaInfo.h.
Referenced by GetAnaInfoFile(), main(), VerifyOptions(), and ~AnaInfo().
FILE* AnaInfo::fFileStdLog
Definition at line 51 of file AnaInfo.h.
Referenced by ~AnaInfo().
std::string AnaInfo::fFileStdLogName
Definition at line 52 of file AnaInfo.h.
Referenced by GetStdLogFileName(), PrintAsPhp(), MAsymAnaInfo::ProcessOptions(), MAlphaAnaInfo::ProcessOptions(), AsymAnaInfo::ProcessOptions(), and VerifyOptions().
Bool_t AnaInfo::fFlagCopyResults
Definition at line 53 of file AnaInfo.h.
Referenced by CopyResults(), PrintAsPhp(), MAsymAnaInfo::ProcessOptions(), and AsymAnaInfo::ProcessOptions().
Bool_t AnaInfo::fFlagCreateThumbs
Definition at line 56 of file AnaInfo.h.
Referenced by PrintAsPhp(), MAsymAnaInfo::ProcessOptions(), and AsymAnaInfo::ProcessOptions().
Bool_t AnaInfo::fFlagUpdateDb
Definition at line 55 of file AnaInfo.h.
Referenced by main(), PrintAsPhp(), MAsymAnaInfo::ProcessOptions(), and AsymAnaInfo::ProcessOptions().
Bool_t AnaInfo::fFlagUseDb
Definition at line 54 of file AnaInfo.h.
Referenced by main(), PrintAsPhp(), MAsymAnaInfo::ProcessOptions(), and AsymAnaInfo::ProcessOptions().
ULong_t AnaInfo::fModes
Definition at line 45 of file AnaInfo.h.
Referenced by HasGraphBit(), PrintAsPhp(), MAsymAnaInfo::ProcessOptions(), MAlphaAnaInfo::ProcessOptions(), and AsymAnaInfo::ProcessOptions().
std::string AnaInfo::fOutputName [protected]
Definition at line 39 of file AnaInfo.h.
Referenced by GetOutDir(), GetRootFileName(), PrintAsPhp(), MAsymAnaInfo::VerifyOptions(), MAlphaAnaInfo::VerifyOptions(), AsymAnaInfo::VerifyOptions(), and VerifyOptions().
std::string AnaInfo::fSuffix
Additional unique identifier for analysis job.
Definition at line 44 of file AnaInfo.h.
Referenced by GetSuffix(), main(), PrintAsPhp(), MAsymAnaInfo::ProcessOptions(), and AsymAnaInfo::ProcessOptions().
UserGroup_t AnaInfo::fUserGroup
Definition at line 57 of file AnaInfo.h.
Referenced by EventConfig::GetSignature(), Init(), PrintAsPhp(), and MAsymSingleFillHists::SetSignature().
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/AnaInfo.h
/direct/eic+u/dsmirnov/cnipol/src/AnaInfo.cxx