cnipol: AsymCalculator Class Reference
AsymCalculator Class Reference
#include <AsymCalculator.h>
Public Member Functions
void CalcBunchAsym (DrawObjContainer *oc)
void CalcBunchAsymSqrtFormula (DrawObjContainer *oc)
void CalcDelimAsym (DrawObjContainer *oc)
void CalcDelimAsymSqrtFormula (DrawObjContainer *oc)
void CalcOscillPhaseAsymSqrtFormula (TH2 &h2DetCounts_up, TH2 &h2DetCounts_down, TH1 &hAsym, DetLRSet detSet)
Takes event counts per detector for up and down spin state bunches and calculates the geom, lumi, and phys asymmetries for each bin along the X axis.
TGraphErrors * CalcBunchAsymDet (TH2 &hDetVsBunchId_ss, TH2 &hDetVsBunchId, DetLRSet detSet, TGraphErrors *gr=0)
Calculates the left-right asymmetry for a given set of detectors detSet.
TGraphErrors * CalcBunchAsymX90 (TH2 &hDetVsBunchId_ss, TH2 &hDetVsBunchId, TGraphErrors *gr=0)
TGraphErrors * CalcBunchAsymX45 (TH2 &hDetVsBunchId_ss, TH2 &hDetVsBunchId, TGraphErrors *gr=0)
TGraphErrors * CalcBunchAsymY45 (TH2 &hDetVsBunchId_ss, TH2 &hDetVsBunchId, TGraphErrors *gr=0)
ValErrMap CalcDetAsymSqrtFormula (TH1 &hUp, TH1 &hDown, DetLRSet detSet)
Calculates three asymmetries using the square root formula from two histogram containing counts per detector.
ValErrMap CalcDetAsymX90SqrtFormula (TH1 &hUp, TH1 &hDown)
ValErrMap CalcDetAsymX45SqrtFormula (TH1 &hUp, TH1 &hDown)
ValErrMap CalcDetAsymX45TSqrtFormula (TH1 &hUp, TH1 &hDown)
ValErrMap CalcDetAsymX45BSqrtFormula (TH1 &hUp, TH1 &hDown)
ValErrMap CalcDetAsymY45SqrtFormula (TH1 &hUp, TH1 &hDown)
void CalcStripAsymmetry (DrawObjContainer *oc)
This method is called from the histogram container.
void CalcStripAsymmetryByProfile (DrawObjContainer *oc)
void CalcKinEnergyAChAsym (DrawObjContainer *oc)
void CalcLongiChAsym (DrawObjContainer *oc)
void CalcStripAsymmetry (int Mode)
Calculates asymmetries strip by strip.
TH1D * CalcChannelAsym (TH1I &hUp, TH1I &hDown, TH1D *hChAsym=0)
Takes two histograms binned by channel for spin up and down.
TFitResultPtr FitChAsymConst (TH1D &hChAsym, TGraphErrors *gr=0)
TFitResultPtr FitChAsymSine (TH1D &hChAsym, TGraphErrors *gr=0)
Matches channels (and their asymmetries) from hChAsym to phi angles in TGraphErrors gr.
void SinPhiFit (Float_t p0, Float_t *RawP, Float_t *dRawP, Float_t *P, Float_t *phase, Float_t &chi2dof)
void ScanSinPhiFit (Float_t p0, Float_t *RawP, Float_t *dRawP, Float_t *P, Float_t *phase, Float_t &chi2dof)
Static Public Member Functions
static void CumulativeAsymmetry (long *nGood, long *nTotal, long *nBack)
Calculates bunch cumulative asymmetries.
static Float_t WeightAnalyzingPower (int hid)
static Bool_t IsExclusionCandidate (int i, int j)
static ValErrPair CalcAsym (Double_t A, Double_t B, Double_t totalA, Double_t totalB)
static ValErrPair CalcAsymSqrtFormula (Double_t A, Double_t B, Double_t C, Double_t D)
static void sqass (Double_t A, Double_t B, Double_t C, Double_t D, Double_t &asym, Double_t &asymErr)
static void CalcStatistics ()
static void PrintWarning ()
static void PrintRunResults ()
static void DrawPlotvsTar ()
static void SpecificLuminosity (long *nGood)
Handle Specific Luminosity.
Static Public Attributes
static DetLRSet X90Dets
static DetLRSet X45Dets
static DetLRSet X45TDets
static DetLRSet X45BDets
static DetLRSet Y45Dets
Detailed Description
Definition at line 30 of file AsymCalculator.h.
Member Function Documentation
ValErrPair AsymCalculator::CalcAsym (Double_t A, Double_t B, Double_t totalA, Double_t totalB) [static]
Definition at line 1401 of file AsymCalculator.cxx.
Referenced by CalcBunchAsymDet(), CalcChannelAsym(), and CalcStripAsymmetry().
ValErrPair AsymCalculator::CalcAsymSqrtFormula (Double_t A, Double_t B, Double_t C, Double_t D) [static]
Definition at line 1424 of file AsymCalculator.cxx.
Referenced by CalcDetAsymSqrtFormula(), and sqass().
void AsymCalculator::CalcBunchAsym (DrawObjContainer * oc)
Definition at line 1168 of file AsymCalculator.cxx.
Referenced by CnipolAsymHists::FillDerived().
TGraphErrors * AsymCalculator::CalcBunchAsymDet (TH2 & hDetVsBunchId_ss, TH2 & hDetVsBunchId, DetLRSet detSet, TGraphErrors * gr = 0)
Calculates the left-right asymmetry for a given set of detectors detSet.
All the counts are given by the hDetVsBunchId_ss histogram, and the normalization is calculated from all the counts in the hDetVsBunchId histogram.
Definition at line 75 of file AsymCalculator.cxx.
Referenced by CalcBunchAsymX45(), CalcBunchAsymX90(), and CalcBunchAsymY45().
void AsymCalculator::CalcBunchAsymSqrtFormula (DrawObjContainer * oc)
Definition at line 1276 of file AsymCalculator.cxx.
Referenced by CnipolAsymHists::FillDerived().
TGraphErrors * AsymCalculator::CalcBunchAsymX45 (TH2 & hDetVsBunchId_ss, TH2 & hDetVsBunchId, TGraphErrors * gr = 0)
Definition at line 130 of file AsymCalculator.cxx.
Referenced by CalcBunchAsym().
TGraphErrors * AsymCalculator::CalcBunchAsymX90 (TH2 & hDetVsBunchId_ss, TH2 & hDetVsBunchId, TGraphErrors * gr = 0)
Definition at line 119 of file AsymCalculator.cxx.
Referenced by CalcBunchAsym().
TGraphErrors * AsymCalculator::CalcBunchAsymY45 (TH2 & hDetVsBunchId_ss, TH2 & hDetVsBunchId, TGraphErrors * gr = 0)
Definition at line 147 of file AsymCalculator.cxx.
Referenced by CalcBunchAsym().
TH1D * AsymCalculator::CalcChannelAsym (TH1I & hUp, TH1I & hDown, TH1D * hChAsym = 0)
Takes two histograms binned by channel for spin up and down.
Returns a hist filled with asym values for each valid channel.
Definition at line 1928 of file AsymCalculator.cxx.
Referenced by CalcKinEnergyAChAsym(), CalcLongiChAsym(), CalcStripAsymmetry(), and CalcStripAsymmetryByProfile().
void AsymCalculator::CalcDelimAsym (DrawObjContainer * oc)
Definition at line 1296 of file AsymCalculator.cxx.
void AsymCalculator::CalcDelimAsymSqrtFormula (DrawObjContainer * oc)
Definition at line 1328 of file AsymCalculator.cxx.
Referenced by CnipolAsymHists::FillDerived().
ValErrMap AsymCalculator::CalcDetAsymSqrtFormula (TH1 & hUp, TH1 & hDown, DetLRSet detSet)
Calculates three asymmetries using the square root formula from two histogram containing counts per detector.
Definition at line 167 of file AsymCalculator.cxx.
Referenced by CalcBunchAsymSqrtFormula(), CalcDetAsymX45BSqrtFormula(), CalcDetAsymX45SqrtFormula(), CalcDetAsymX45TSqrtFormula(), CalcDetAsymX90SqrtFormula(), CalcDetAsymY45SqrtFormula(), and CalcOscillPhaseAsymSqrtFormula().
ValErrMap AsymCalculator::CalcDetAsymX45BSqrtFormula (TH1 & hUp, TH1 & hDown)
Definition at line 225 of file AsymCalculator.cxx.
Referenced by CalcBunchAsymSqrtFormula().
ValErrMap AsymCalculator::CalcDetAsymX45SqrtFormula (TH1 & hUp, TH1 & hDown)
Definition at line 202 of file AsymCalculator.cxx.
Referenced by CalcBunchAsymSqrtFormula(), and CalcDelimAsymSqrtFormula().
ValErrMap AsymCalculator::CalcDetAsymX45TSqrtFormula (TH1 & hUp, TH1 & hDown)
Definition at line 214 of file AsymCalculator.cxx.
ValErrMap AsymCalculator::CalcDetAsymX90SqrtFormula (TH1 & hUp, TH1 & hDown)
Definition at line 191 of file AsymCalculator.cxx.
Referenced by CalcBunchAsymSqrtFormula(), and CalcDelimAsymSqrtFormula().
ValErrMap AsymCalculator::CalcDetAsymY45SqrtFormula (TH1 & hUp, TH1 & hDown)
Definition at line 236 of file AsymCalculator.cxx.
Referenced by CalcBunchAsymSqrtFormula().
void AsymCalculator::CalcKinEnergyAChAsym (DrawObjContainer * oc)
Definition at line 1690 of file AsymCalculator.cxx.
Referenced by CnipolAsymHists::FillDerived().
void AsymCalculator::CalcLongiChAsym (DrawObjContainer * oc)
Definition at line 1724 of file AsymCalculator.cxx.
Referenced by CnipolAsymHists::FillDerived().
void AsymCalculator::CalcOscillPhaseAsymSqrtFormula (TH2 & h2DetCounts_up, TH2 & h2DetCounts_down, TH1 & hAsym, DetLRSet detSet)
Takes event counts per detector for up and down spin state bunches and calculates the geom, lumi, and phys asymmetries for each bin along the X axis.
Returns the results as graphs saved in the dummy hAsym histogram.
Definition at line 1364 of file AsymCalculator.cxx.
Referenced by CnipolSpinStudyHists::PostFill().
void AsymCalculator::CalcStatistics () [static]
Definition at line 648 of file AsymCalculator.cxx.
Referenced by RawDataReader::ReadDataPassTwo().
void AsymCalculator::CalcStripAsymmetry (int Mode)
Calculates asymmetries strip by strip.
This method updates the global object gAnaMeasResult with a calculated polarization value for the give strip.
Definition at line 1763 of file AsymCalculator.cxx.
void AsymCalculator::CalcStripAsymmetry (DrawObjContainer * oc)
This method is called from the histogram container.
This is the main method to calculate the asymmetry
Definition at line 1550 of file AsymCalculator.cxx.
Referenced by CnipolAsymHists::FillDerived().
void AsymCalculator::CalcStripAsymmetryByProfile (DrawObjContainer * oc)
Definition at line 1649 of file AsymCalculator.cxx.
Referenced by CnipolAsymHists::FillDerived().
void AsymCalculator::CumulativeAsymmetry (long * nGood, long * nTotal, long * nBack) [static]
Calculates bunch cumulative asymmetries.
Parameters:
nGood number of events after carbon cut (each bunch)
nTotal number of events before carbon cut (each bunch)
nBack number of events below the curbon cut (each bunch)
The size of the above arrays is assumed to be equal to N_BUNCHES
Definition at line 256 of file AsymCalculator.cxx.
void AsymCalculator::DrawPlotvsTar () [static]
Definition at line 786 of file AsymCalculator.cxx.
TFitResultPtr AsymCalculator::FitChAsymConst (TH1D & hChAsym, TGraphErrors * gr = 0)
Definition at line 1977 of file AsymCalculator.cxx.
TFitResultPtr AsymCalculator::FitChAsymSine (TH1D & hChAsym, TGraphErrors * gr = 0)
Matches channels (and their asymmetries) from hChAsym to phi angles in TGraphErrors gr.
The sine is then fit to the graph.
Definition at line 2015 of file AsymCalculator.cxx.
Referenced by CalcKinEnergyAChAsym(), CalcLongiChAsym(), CalcStripAsymmetry(), and CalcStripAsymmetryByProfile().
Bool_t AsymCalculator::IsExclusionCandidate (int i, int j) [static]
Definition at line 944 of file AsymCalculator.cxx.
Referenced by CalcChannelAsym(), and CalcStripAsymmetry().
void AsymCalculator::PrintRunResults () [static]
Definition at line 727 of file AsymCalculator.cxx.
Referenced by RawDataReader::ReadDataPassTwo().
void AsymCalculator::PrintWarning () [static]
Definition at line 675 of file AsymCalculator.cxx.
Referenced by RawDataReader::ReadDataPassTwo().
void AsymCalculator::ScanSinPhiFit (Float_t p0, Float_t * RawP, Float_t * dRawP, Float_t * P, Float_t * phase, Float_t & chi2dof)
Definition at line 2123 of file AsymCalculator.cxx.
void AsymCalculator::SinPhiFit (Float_t p0, Float_t * RawP, Float_t * dRawP, Float_t * P, Float_t * phase, Float_t & chi2dof)
Definition at line 2059 of file AsymCalculator.cxx.
Referenced by CalcStripAsymmetry().
void AsymCalculator::SpecificLuminosity (long * nGood) [static]
Handle Specific Luminosity.
Parameters:
nGood number of events after carbon cut (each bunch)
Definition at line 968 of file AsymCalculator.cxx.
void AsymCalculator::sqass (Double_t A, Double_t B, Double_t C, Double_t D, Double_t & asym, Double_t & asymErr) [static]
Definition at line 1446 of file AsymCalculator.cxx.
Referenced by CumulativeAsymmetry().
Float_t AsymCalculator::WeightAnalyzingPower (int hid) [static]
Definition at line 816 of file AsymCalculator.cxx.
Referenced by RawDataReader::ReadDataPassTwo().
Member Data Documentation
DetLRSet AsymCalculator::X45BDets [static]
Definition at line 45 of file AsymCalculator.h.
DetLRSet AsymCalculator::X45Dets [static]
Definition at line 43 of file AsymCalculator.h.
Referenced by CnipolSpinStudyHists::PostFill().
DetLRSet AsymCalculator::X45TDets [static]
Definition at line 44 of file AsymCalculator.h.
Referenced by CalcBunchAsymSqrtFormula().
DetLRSet AsymCalculator::X90Dets [static]
Definition at line 42 of file AsymCalculator.h.
DetLRSet AsymCalculator::Y45Dets [static]
Definition at line 46 of file AsymCalculator.h.
Referenced by CnipolSpinStudyHists::PostFill().
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/AsymCalculator.h
/direct/eic+u/dsmirnov/cnipol/src/AsymCalculator.cxx