cnipol: CnipolProfileHists Class Reference
CnipolProfileHists Class Reference
#include <CnipolProfileHists.h>
Public Member Functions
CnipolProfileHists ()
Default constructor.
CnipolProfileHists (TDirectory *dir)
~CnipolProfileHists ()
Default destructor.
void BookHists ()
void PreFill ()
void Fill (ChannelEvent *ch)
void Fill (UInt_t n, int32_t *hData)
void PostFill ()
void FillDerived (DrawObjContainer &oc)
EMeasType GuessMeasurementType ()
Double_t ProfileFitFunc (Double_t *x, Double_t *par)
Double_t ProfileTailFitFunc (Double_t *x, Double_t *par)
Public Member Functions inherited from DrawObjContainer
bool PrepareHistogram (TCanvas *canvas, TH1 *hobj)
DrawObjContainer ()
Default constructor.
DrawObjContainer (TDirectory *dir)
virtual ~DrawObjContainer ()
Default destructor.
std::string GetSignature () const
virtual void SetSignature (const std::string signature)
void SetDir (TDirectory *dir)
void ReadFromDir ()
void ReadFromDir (TDirectory *dir)
void Add (DrawObjContainer *oc)
Recursively adds objects (histograms) from another DrawObjContainer to this one.
virtual void Fill (EventConfig &rc)
virtual void Fill (const EventConfig &rc)
virtual void Fill (EventConfig &rc, DrawObjContainer &oc)
void Print (const Option_t *opt="") const
virtual void FillPassOne (ChannelEvent *ch)
virtual void FillDerivedPassOne ()
virtual void FillDerivedPassOne (DrawObjContainer &oc)
virtual void PostFillPassOne (DrawObjContainer *oc=0)
virtual void FillDerived ()
virtual void PostFill (AnaGlobResult &agr)
virtual void PostFill (DrawObjContainer *oc)
virtual void SaveAllAs (ImageFormat fmt_ext, TCanvas &c, std::string pattern="^.*$", std::string path="./", Bool_t thumbs=kFALSE)
virtual void SaveHStackAs (TCanvas &c, THStack &hstack, std::string path="./")
void Draw (Option_t *option="")
void Draw (TCanvas &c)
Int_t Write (const char *name=0, Int_t option=0, Int_t bufsize=0)
Int_t Write (const char *name=0, Int_t option=0, Int_t bufsize=0) const
void Delete (Option_t *option="")
virtual void UpdateLimits ()
Additional Inherited Members
Public Types inherited from DrawObjContainer
typedef const char * ImageFormat
Public Attributes inherited from DrawObjContainer
TDirectory * fDir
ObjMap o
DrawObjContainerMap d
Static Public Attributes inherited from DrawObjContainer
static ImageFormat FORMAT_PNG = ".png"
static ImageFormat FORMAT_POSTSCRIPT = ".ps"
static ImageFormat FORMAT_EPS = ".eps"
Protected Attributes inherited from DrawObjContainer
std::string fSignature
Detailed Description
Definition at line 23 of file CnipolProfileHists.h.
Constructor & Destructor Documentation
CnipolProfileHists::CnipolProfileHists ()
Default constructor.
Definition at line 23 of file CnipolProfileHists.cxx.
CnipolProfileHists::CnipolProfileHists (TDirectory * dir)
Definition at line 29 of file CnipolProfileHists.cxx.
CnipolProfileHists::~CnipolProfileHists ()
Default destructor.
Definition at line 36 of file CnipolProfileHists.cxx.
Member Function Documentation
void CnipolProfileHists::BookHists ()
Definition at line 42 of file CnipolProfileHists.cxx.
Referenced by CnipolProfileHists().
void CnipolProfileHists::Fill (ChannelEvent * ch) virtual
Reimplemented from DrawObjContainer.
Definition at line 349 of file CnipolProfileHists.cxx.
void CnipolProfileHists::Fill (UInt_t n, int32_t * hData)
Definition at line 364 of file CnipolProfileHists.cxx.
void CnipolProfileHists::FillDerived (DrawObjContainer & oc) virtual
Reimplemented from DrawObjContainer.
Definition at line 405 of file CnipolProfileHists.cxx.
EMeasType CnipolProfileHists::GuessMeasurementType ()
Definition at line 815 of file CnipolProfileHists.cxx.
Referenced by PostFill().
void CnipolProfileHists::PostFill () virtual
Reimplemented from DrawObjContainer.
Definition at line 454 of file CnipolProfileHists.cxx.
void CnipolProfileHists::PreFill () virtual
Reimplemented from DrawObjContainer.
Definition at line 330 of file CnipolProfileHists.cxx.
Double_t CnipolProfileHists::ProfileFitFunc (Double_t * x, Double_t * par)
Definition at line 848 of file CnipolProfileHists.cxx.
Referenced by PostFill(), and ProfileTailFitFunc().
Double_t CnipolProfileHists::ProfileTailFitFunc (Double_t * x, Double_t * par)
Definition at line 864 of file CnipolProfileHists.cxx.
Referenced by PostFill().
The documentation for this class was generated from the following files:
inc/CnipolProfileHists.h
src/CnipolProfileHists.cxx