cnipol: MAsymAnaInfo Class Reference
MAsymAnaInfo Class Reference
This class takes care of the command line options specific to the 'masym' executable.
#include <MAsymAnaInfo.h>
Public Types
enum Option { OPTION_MLIST = 0x20000001 }
Public Types inherited from AnaInfo
enum Flag {
FLAG_COPY = 0x10000400, FLAG_READ_FROM_DB = 0x10000100, FLAG_UPDATE_DB = 0x10000200, FLAG_NO_UPDATE_DB = 0x90000200,
FLAG_USE_DB = 0x10000300, FLAG_CREATE_THUMBS = 0x10000800
}
enum Option {
OPTION_POL_ID = 0x20004000, OPTION_SET_CALIB_ALPHA = 0x20001000, OPTION_DET_DISABLE = 0x20000001, OPTION_SUFFIX = 0x20000002,
OPTION_ALPHA_SOURCES = 0x20000003
}
enum Mode { MODE_GRAPH = 0x02000000, MODE_NO_GRAPH = 0x82000000 }
Public Member Functions
MAsymAnaInfo ()
void SetMListFileName (std::string listName)
std::string GetMListFileName ()
std::string GetMListFullPath ()
std::string GetExternInfoPath ()
void ProcessOptions (int argc, char **argv)
void VerifyOptions ()
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
void PrintUsage ()
Public Member Functions inherited from AnaInfo
AnaInfo ()
~AnaInfo ()
std::string GetSuffix () const
std::string GetResultsDir () const
std::string GetOutDir () const
std::string GetSlowControlLogDir () const
std::string GetImageDir () const
virtual std::string GetAnaInfoFileName () const
std::string GetStdLogFileName () const
std::string GetRootFileName () const
FILE * GetAnaInfoFile () const
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
virtual void CopyResults ()
Bool_t HasGraphBit () const
Public Attributes
std::string fMListFileName
Public Attributes inherited from AnaInfo
std::string fAsymVersion
std::string fSuffix
ULong_t fModes
time_t fAnaDateTime
Double_t fAnaTimeReal
Double_t fAnaTimeCpu
Str2StrMap fAsymEnv
FILE * fFileMeasInfo
FILE * fFileStdLog
std::string fFileStdLogName
Bool_t fFlagCopyResults
Bool_t fFlagUseDb
Bool_t fFlagUpdateDb
Bool_t fFlagCreateThumbs
UserGroup_t fUserGroup
Short_t fAlphaSourceCount
Additional Inherited Members
Protected Member Functions inherited from AnaInfo
void Init ()
void MakeOutDir ()
Protected Attributes inherited from AnaInfo
std::string fOutputName
Detailed Description
This class takes care of the command line options specific to the 'masym' executable.
The common options are taken care of by the AnaInfo class.
Definition at line 20 of file MAsymAnaInfo.h.
Member Enumeration Documentation
enum MAsymAnaInfo::Option
Enumerator
OPTION_MLIST
Definition at line 25 of file MAsymAnaInfo.h.
Constructor & Destructor Documentation
MAsymAnaInfo::MAsymAnaInfo ()
Definition at line 18 of file MAsymAnaInfo.cxx.
Member Function Documentation
string MAsymAnaInfo::GetExternInfoPath ()
Definition at line 28 of file MAsymAnaInfo.cxx.
Referenced by AnaGlobResult::Configure().
string MAsymAnaInfo::GetMListFileName ()
Definition at line 26 of file MAsymAnaInfo.cxx.
string MAsymAnaInfo::GetMListFullPath ()
Definition at line 27 of file MAsymAnaInfo.cxx.
Referenced by main(), and VerifyOptions().
void MAsymAnaInfo::Print (const Option_t * opt = "") const
Definition at line 133 of file MAsymAnaInfo.cxx.
void MAsymAnaInfo::PrintAsPhp (FILE * f = stdout) const
Definition at line 141 of file MAsymAnaInfo.cxx.
Referenced by Print().
void MAsymAnaInfo::PrintUsage () virtual
Reimplemented from AnaInfo.
Definition at line 150 of file MAsymAnaInfo.cxx.
Referenced by ProcessOptions(), and VerifyOptions().
void MAsymAnaInfo::ProcessOptions (int argc, char ** argv) virtual
Reimplemented from AnaInfo.
Definition at line 32 of file MAsymAnaInfo.cxx.
Referenced by main().
void MAsymAnaInfo::SetMListFileName (std::string listName)
Definition at line 25 of file MAsymAnaInfo.cxx.
Referenced by ProcessOptions().
void MAsymAnaInfo::VerifyOptions () virtual
Reimplemented from AnaInfo.
Definition at line 106 of file MAsymAnaInfo.cxx.
Referenced by main().
Member Data Documentation
std::string MAsymAnaInfo::fMListFileName
Definition at line 28 of file MAsymAnaInfo.h.
Referenced by GetMListFileName(), GetMListFullPath(), PrintAsPhp(), SetMListFileName(), and VerifyOptions().
The documentation for this class was generated from the following files:
inc/MAsymAnaInfo.h
src/MAsymAnaInfo.cxx