cnipol: RunConfig Class Reference
RunConfig Class Reference
#include <RunConfig.h>
Public Member Functions
RunConfig ()
~RunConfig ()
void SetBeamEnergies (BeamEnergySet beamEnergies)
Static Public Member Functions
static std::string AsString (EPolarimeterId polId)
static std::string AsString (EMeasType measType)
static std::string AsString (ETargetOrient targetOrient)
static std::string AsString (EBeamId beamId)
static std::string AsString (ERingId ringId)
static std::string AsString (EBeamEnergy beamEnergy)
static std::string AsString (ESpinState spinState)
static std::string AsString (EAsymType asymType)
static UShort_t AsIndex (ESpinState spinState)
static Color_t AsColor (EBeamId beamId)
static Color_t AsColor (ERingId ringId)
static Color_t AsColor (EPolarimeterId polId)
static Color_t AsColor (ESpinState spin)
static Color_t AsColor (EAsymType asymType)
static Color_t AsColor (UShort_t chId)
static TAttMarker AsMarker (ETargetOrient targetOrient, EPolarimeterId polId)
static EBeamId GetBeamId (EPolarimeterId polId)
static ERingId GetRingId (EPolarimeterId polId)
static EStreamId GetStreamId (EPolarimeterId polId)
static UShort_t GetDetectorId (UShort_t chId)
static UShort_t GetDetectorChannelId (UShort_t chId)
static std::string GetBiasCurrentLoggerName (EPolarimeterId polId)
Public Attributes
PolarimeterIdSet fPolarimeters
TargetSet fTargets
std::set< EMeasType > fMeasTypes
std::set< ETargetOrient > fTargetOrients
BeamIdSet fBeams
std::set< ERingId > fRings
BeamEnergySet fBeamEnergies
SpinStateSet fSpinStates
AsymTypeSet fAsymTypes
Detailed Description
Definition at line 16 of file RunConfig.h.
Constructor & Destructor Documentation
RunConfig::RunConfig ()
Definition at line 26 of file RunConfig.cxx.
RunConfig::~RunConfig ()
Definition at line 79 of file RunConfig.cxx.
Member Function Documentation
Color_t RunConfig::AsColor (UShort_t chId) [static]
Definition at line 307 of file RunConfig.cxx.
Color_t RunConfig::AsColor (EAsymType asymType) [static]
Definition at line 291 of file RunConfig.cxx.
Color_t RunConfig::AsColor (ESpinState spin) [static]
Definition at line 275 of file RunConfig.cxx.
Color_t RunConfig::AsColor (EPolarimeterId polId) [static]
Definition at line 259 of file RunConfig.cxx.
Color_t RunConfig::AsColor (ERingId ringId) [static]
Definition at line 245 of file RunConfig.cxx.
Color_t RunConfig::AsColor (EBeamId beamId) [static]
Definition at line 231 of file RunConfig.cxx.
Referenced by AsMarker(), MAsymRunHists::BookHists(), CnipolSpinStudyHists::BookHists(), CnipolPreprocHists::BookHists(), CnipolAsymHists::BookHists(), MAsymSingleFillHists::BookHistsByPolarimeter(), MAsymRunHists::BookHistsByPolarimeter(), MAsymFillHists::BookHistsByPolarimeter(), MAsymSingleFillHists::BookHistsByRing(), MAsymRunHists::BookHistsByRing(), MAsymFillHists::BookHistsByRing(), MAsymRateHists::BookHistsPolarimeter(), MAsymPmtHists::BookHistsPolarimeter(), MAsymSingleFillHists::PostFill(), and CnipolAsymHists::PostFill().
UShort_t RunConfig::AsIndex (ESpinState spinState) [static]
Definition at line 215 of file RunConfig.cxx.
Referenced by CnipolHists::BookHists(), and CnipolHists::Fill().
TAttMarker RunConfig::AsMarker (ETargetOrient targetOrient, EPolarimeterId polId) [static]
Definition at line 332 of file RunConfig.cxx.
Referenced by MAsymRunHists::BookHistsByPolarimeter(), and MAsymSingleFillHists::PostFill().
string RunConfig::AsString (EAsymType asymType) [static]
Definition at line 199 of file RunConfig.cxx.
string RunConfig::AsString (ESpinState spinState) [static]
Definition at line 183 of file RunConfig.cxx.
string RunConfig::AsString (EBeamEnergy beamEnergy) [static]
Definition at line 165 of file RunConfig.cxx.
string RunConfig::AsString (ERingId ringId) [static]
Definition at line 151 of file RunConfig.cxx.
string RunConfig::AsString (EBeamId beamId) [static]
Definition at line 137 of file RunConfig.cxx.
string RunConfig::AsString (ETargetOrient targetOrient) [static]
Definition at line 123 of file RunConfig.cxx.
string RunConfig::AsString (EMeasType measType) [static]
Definition at line 103 of file RunConfig.cxx.
string RunConfig::AsString (EPolarimeterId polId) [static]
Definition at line 85 of file RunConfig.cxx.
Referenced by MAsymRunHists::AdjustMinMaxFill(), MAsymRunHists::BookHists(), CnipolSpinStudyHists::BookHists(), CnipolHists::BookHists(), CnipolAsymHists::BookHists(), MAsymSingleFillHists::BookHistsByPolarimeter(), MAsymRunHists::BookHistsByPolarimeter(), MAsymFillHists::BookHistsByPolarimeter(), MAsymSingleFillHists::BookHistsByRing(), MAsymRunHists::BookHistsByRing(), MAsymFillHists::BookHistsByRing(), MAsymRateHists::BookHistsPolarimeter(), MAsymPmtHists::BookHistsPolarimeter(), AnaFillResult::CalcAvrgAsymByBunch(), AsymCalculator::CalcBunchAsym(), AsymCalculator::CalcOscillPhaseAsymSqrtFormula(), AnaGlobResult::CalcPolarNorm(), MAsymRunHists::Fill(), MAsymRateHists::Fill(), MAsymPmtHists::Fill(), MAsymFillHists::Fill(), CnipolSpinStudyHists::Fill(), CnipolHists::Fill(), CnipolAsymHists::Fill(), CnipolSpinStudyHists::FillDerived(), CnipolHists::FillDerived(), CnipolAsymHists::FillDerived(), main(), operator<<(), MAsymSingleFillHists::PostFill(), MAsymRunHists::PostFill(), MAsymFillHists::PostFill(), CnipolSpinStudyHists::PostFill(), CnipolAsymHists::PostFill(), CnipolAsymHists::PreFill(), AnaGlobResult::Print(), AnaFillResult::Print(), AnaGlobResult::PrintAsPhp(), MAsymRunHists::UpdateLimits(), MAsymPmtHists::UpdateLimits(), and MAsymFillHists::UpdateLimits().
EBeamId RunConfig::GetBeamId (EPolarimeterId polId) [static]
Definition at line 357 of file RunConfig.cxx.
Referenced by FillBeamCurrent(), and BiasCurrentUtil::GetBiasCurrentLoggerName().
static std::string RunConfig::GetBiasCurrentLoggerName (EPolarimeterId polId) [static]
UShort_t RunConfig::GetDetectorChannelId (UShort_t chId) [static]
Definition at line 422 of file RunConfig.cxx.
Referenced by AsColor().
UShort_t RunConfig::GetDetectorId (UShort_t chId) [static]
Definition at line 411 of file RunConfig.cxx.
Referenced by AsColor(), CnipolSpinStudyHists::FillDerived(), CnipolAsymHists::FillDerived(), and GetDetectorChannelId().
ERingId RunConfig::GetRingId (EPolarimeterId polId) [static]
Definition at line 375 of file RunConfig.cxx.
Referenced by AnaFillResult::CalcAvrgPolar(), AnaFillResult::CalcBeamPolar(), AnaGlobResult::CalcDependencies(), AnaGlobResult::CalcPolarNorm(), AnaFillResult::CalcSystJvsCPolar(), AnaFillResult::GetHJAsym(), AnaFillResult::GetHJPolar(), MAsymRunHists::PostFill(), MAsymFillHists::PostFill(), AnaFillResult::Process(), and AnaGlobResult::UpdateInsertDb().
EStreamId RunConfig::GetStreamId (EPolarimeterId polId) [static]
Definition at line 393 of file RunConfig.cxx.
void RunConfig::SetBeamEnergies (BeamEnergySet beamEnergies)
Definition at line 433 of file RunConfig.cxx.
Referenced by main().
Member Data Documentation
AsymTypeSet RunConfig::fAsymTypes
Definition at line 29 of file RunConfig.h.
Referenced by CnipolSpinStudyHists::BookHists(), AsymCalculator::CalcOscillPhaseAsymSqrtFormula(), CnipolSpinStudyHists::PostFill(), and RunConfig().
BeamEnergySet RunConfig::fBeamEnergies
Definition at line 27 of file RunConfig.h.
Referenced by MAsymRunHists::AdjustMinMaxFill(), MAsymRunHists::BookHists(), MAsymRateHists::Fill(), MAsymPmtHists::Fill(), main(), MAsymRunHists::PostFill(), RunConfig(), SetBeamEnergies(), MAsymRunHists::UpdateLimits(), and MAsymPmtHists::UpdateLimits().
BeamIdSet RunConfig::fBeams
Definition at line 25 of file RunConfig.h.
Referenced by RunConfig().
std::set<EMeasType> RunConfig::fMeasTypes
Definition at line 23 of file RunConfig.h.
Referenced by RunConfig().
PolarimeterIdSet RunConfig::fPolarimeters
Definition at line 21 of file RunConfig.h.
Referenced by MAsymRunHists::AdjustMinMaxFill(), AnaFillResult::AnaFillResult(), AnaGlobResult::AnaGlobResult(), MAsymSingleFillHists::BookHists(), MAsymRunHists::BookHists(), MAsymFillHists::BookHists(), AnaGlobResult::CalcAvrgPolProfR(), AnaFillResult::CalcBeamPolar(), AnaGlobResult::CalcDependencies(), AnaGlobResult::CalcPolarNorm(), AnaFillResult::CalcRampPCPolarRatio(), MeasInfo::ExtractPolarimeterId(), AnaFillResult::FitPCPolarGraphs(), AnaFillResult::FitPCProfRGraphs(), main(), MAsymSingleFillHists::PostFill(), MAsymRunHists::PostFill(), MAsymFillHists::PostFill(), AnaGlobResult::Print(), AnaFillResult::Print(), AnaFillResult::Process(), RunConfig(), AnaGlobResult::UpdateInsertDb(), MAsymRunHists::UpdateLimits(), MAsymPmtHists::UpdateLimits(), and MAsymFillHists::UpdateLimits().
std::set<ERingId> RunConfig::fRings
Definition at line 26 of file RunConfig.h.
Referenced by MAsymRunHists::AdjustMinMaxFill(), MAsymSingleFillHists::BookHists(), MAsymRunHists::BookHists(), MAsymFillHists::BookHists(), AnaFillResult::FitExternGraphs(), MAsymSingleFillHists::PostFill(), MAsymRunHists::PostFill(), MAsymFillHists::PostFill(), RunConfig(), AnaFillResult::UpdateExternGraphRange(), AnaGlobResult::UpdateInsertDb(), and MAsymFillHists::UpdateLimits().
SpinStateSet RunConfig::fSpinStates
Definition at line 28 of file RunConfig.h.
Referenced by CnipolSpinStudyHists::BookHists(), CnipolHists::BookHists(), CnipolAsymHists::BookHists(), MAsymSingleFillHists::BookHistsByRing(), MAsymFillHists::BookHistsByRing(), AnaFillResult::CalcAvrgAsymByBunch(), AsymCalculator::CalcBunchAsym(), CnipolSpinStudyHists::FillDerived(), CnipolHists::FillDerived(), CnipolAsymHists::FillDerived(), MAsymSingleFillHists::PostFill(), MAsymFillHists::PostFill(), CnipolAsymHists::PostFill(), CnipolAsymHists::PreFill(), and RunConfig().
std::set<ETargetOrient> RunConfig::fTargetOrients
Definition at line 24 of file RunConfig.h.
Referenced by AnaGlobResult::CalcAvrgPolProfR(), AnaFillResult::FitPCProfRGraphs(), MAsymSingleFillHists::PostFill(), MAsymRunHists::PostFill(), AnaGlobResult::Print(), AnaFillResult::Process(), RunConfig(), and AnaGlobResult::UpdateInsertDb().
TargetSet RunConfig::fTargets
Definition at line 22 of file RunConfig.h.
Referenced by AnaFillResult::AnaFillResult(), AnaGlobResult::AnaGlobResult(), AnaGlobResult::Print(), AnaFillResult::Print(), AnaGlobResult::PrintAsPhp(), and RunConfig().
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/RunConfig.h
/direct/eic+u/dsmirnov/cnipol/src/RunConfig.cxx