cnipol: AsymDbSql Class Reference
AsymDbSql Class Reference
select information about run periods from an ascii file.
#include <AsymDbSql.h>
Public Member Functions
AsymDbSql ()
~AsymDbSql ()
void OpenConnection ()
void CloseConnection ()
DbEntry * Select (std::string runName="")
MseMeasInfoX * SelectRun (std::string runName="")
MseFillPolarX * SelectFillPolar (UInt_t fill)
MseFillPolarNewX * SelectFillPolar (UInt_t fill, EPolarimeterId polId, ERingId ringId)
MseFillPolarNewXSet SelectFillPolars (UInt_t fill)
MseFillProfileX * SelectFillProfile (UInt_t fill)
MseFillProfileNewX * SelectFillProfile (UInt_t fill, EPolarimeterId polId, ETargetOrient tgtOrient)
std::vector< MseMeasInfoX > SelectPriorRuns (MseMeasInfoX &run)
MseRunPeriodX * SelectRunPeriod (MseMeasInfoX &run)
Selects the first record corresponding to the time of the provided measurement `run` from the `run_period` table.
void CompleteMeasInfo (MseMeasInfoX &run)
MseRunPeriodX * CompleteMeasInfoByRunPeriod (MseMeasInfoX &run)
Selects the first record corresponding to the time of the provided measurement `run` from the `run_period` table.
void Insert (DbEntry *dbrun)
void UpdateInsert (MseMeasInfoX *orun, MseMeasInfoX *nrun)
void UpdateInsert (MseFillPolarX *ofill, MseFillPolarX *nfill)
void UpdateInsert (MseFillPolarNewX *ofill, MseFillPolarNewX *nfill)
void UpdateInsert (MseFillProfileX *ofill, MseFillProfileX *nfill)
void UpdateInsert (MseFillProfileNewX *ofill, MseFillProfileNewX *nfill)
Public Attributes
mysqlpp::Connection * fConnection
Detailed Description
select information about run periods from an ascii file.
Definition at line 22 of file AsymDbSql.h.
Constructor & Destructor Documentation
AsymDbSql::AsymDbSql ()
Definition at line 12 of file AsymDbSql.cxx.
AsymDbSql::~AsymDbSql ()
Definition at line 24 of file AsymDbSql.cxx.
Member Function Documentation
void AsymDbSql::CloseConnection () [virtual]
Reimplemented from AsymDb.
Definition at line 55 of file AsymDbSql.cxx.
Referenced by SelectRun(), SelectRunPeriod(), UpdateInsert(), AnaGlobResult::UpdateInsertDb(), and ~AsymDbSql().
void AsymDbSql::CompleteMeasInfo (MseMeasInfoX & run) [virtual]
Reimplemented from AsymDb.
Definition at line 318 of file AsymDbSql.cxx.
MseRunPeriodX * AsymDbSql::CompleteMeasInfoByRunPeriod (MseMeasInfoX & run) [virtual]
Selects the first record corresponding to the time of the provided measurement `run` from the `run_period` table.
The returned object is owned by the caller.
Reimplemented from AsymDb.
Definition at line 352 of file AsymDbSql.cxx.
Referenced by main().
void AsymDbSql::Insert (DbEntry * dbrun) [virtual]
Reimplemented from AsymDb.
Definition at line 454 of file AsymDbSql.cxx.
void AsymDbSql::OpenConnection () [virtual]
Reimplemented from AsymDb.
Definition at line 31 of file AsymDbSql.cxx.
Referenced by SelectRun(), SelectRunPeriod(), UpdateInsert(), and AnaGlobResult::UpdateInsertDb().
DbEntry * AsymDbSql::Select (std::string runName = "") [virtual]
Reimplemented from AsymDb.
Definition at line 65 of file AsymDbSql.cxx.
MseFillPolarNewX * AsymDbSql::SelectFillPolar (UInt_t fill, EPolarimeterId polId, ERingId ringId) [virtual]
Reimplemented from AsymDb.
Definition at line 205 of file AsymDbSql.cxx.
MseFillPolarX * AsymDbSql::SelectFillPolar (UInt_t fill) [virtual]
Reimplemented from AsymDb.
Definition at line 174 of file AsymDbSql.cxx.
Referenced by AnaGlobResult::UpdateInsertDb().
MseFillPolarNewXSet AsymDbSql::SelectFillPolars (UInt_t fill)
Definition at line 235 of file AsymDbSql.cxx.
MseFillProfileNewX * AsymDbSql::SelectFillProfile (UInt_t fill, EPolarimeterId polId, ETargetOrient tgtOrient)
Definition at line 288 of file AsymDbSql.cxx.
MseFillProfileX * AsymDbSql::SelectFillProfile (UInt_t fill) [virtual]
Reimplemented from AsymDb.
Definition at line 257 of file AsymDbSql.cxx.
Referenced by AnaGlobResult::UpdateInsertDb().
vector< MseMeasInfoX > AsymDbSql::SelectPriorRuns (MseMeasInfoX & run)
Definition at line 372 of file AsymDbSql.cxx.
Referenced by CompleteMeasInfo().
MseMeasInfoX * AsymDbSql::SelectRun (std::string runName = "") [virtual]
Reimplemented from AsymDb.
Definition at line 106 of file AsymDbSql.cxx.
Referenced by main().
MseRunPeriodX * AsymDbSql::SelectRunPeriod (MseMeasInfoX & run) [virtual]
Selects the first record corresponding to the time of the provided measurement `run` from the `run_period` table.
The returned object is owned by the caller.
Reimplemented from AsymDb.
Definition at line 419 of file AsymDbSql.cxx.
Referenced by CompleteMeasInfoByRunPeriod().
void AsymDbSql::UpdateInsert (MseFillProfileNewX * ofill, MseFillProfileNewX * nfill)
Definition at line 599 of file AsymDbSql.cxx.
void AsymDbSql::UpdateInsert (MseFillProfileX * ofill, MseFillProfileX * nfill) [virtual]
Reimplemented from AsymDb.
Definition at line 575 of file AsymDbSql.cxx.
void AsymDbSql::UpdateInsert (MseFillPolarNewX * ofill, MseFillPolarNewX * nfill) [virtual]
Reimplemented from AsymDb.
Definition at line 551 of file AsymDbSql.cxx.
void AsymDbSql::UpdateInsert (MseFillPolarX * ofill, MseFillPolarX * nfill) [virtual]
Reimplemented from AsymDb.
Definition at line 527 of file AsymDbSql.cxx.
void AsymDbSql::UpdateInsert (MseMeasInfoX * orun, MseMeasInfoX * nrun) [virtual]
Reimplemented from AsymDb.
Definition at line 499 of file AsymDbSql.cxx.
Referenced by main(), and AnaGlobResult::UpdateInsertDb().
Member Data Documentation
mysqlpp::Connection* AsymDbSql::fConnection
Definition at line 27 of file AsymDbSql.h.
Referenced by CloseConnection(), Insert(), OpenConnection(), Select(), SelectFillPolar(), SelectFillPolars(), SelectFillProfile(), SelectPriorRuns(), SelectRun(), SelectRunPeriod(), and UpdateInsert().
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/AsymDbSql.h
/direct/eic+u/dsmirnov/cnipol/src/AsymDbSql.cxx