cnipol: MAsymFillHists Class Reference
MAsymFillHists Class Reference
#include <MAsymFillHists.h>
Public Member Functions
MAsymFillHists ()
Default constructor.
MAsymFillHists (TDirectory *dir)
~MAsymFillHists ()
Default destructor.
void BookHists ()
void BookHistsByPolarimeter (EPolarimeterId polId)
void BookHistsByRing (ERingId ringId)
void Fill (const EventConfig &rc)
void PostFill (AnaGlobResult &agr)
void PostFill ()
void UpdateLimits ()
DrawObjContainer * GetSingleFillHists (const AnaFillResult &afr)
Detailed Description
Definition at line 17 of file MAsymFillHists.h.
Constructor & Destructor Documentation
MAsymFillHists::MAsymFillHists ()
Default constructor.
Definition at line 20 of file MAsymFillHists.cxx.
MAsymFillHists::MAsymFillHists (TDirectory * dir)
Definition at line 26 of file MAsymFillHists.cxx.
MAsymFillHists::~MAsymFillHists ()
Default destructor.
Definition at line 33 of file MAsymFillHists.cxx.
Member Function Documentation
void MAsymFillHists::BookHists ()
Definition at line 41 of file MAsymFillHists.cxx.
Referenced by MAsymFillHists().
void MAsymFillHists::BookHistsByPolarimeter (EPolarimeterId polId)
Definition at line 63 of file MAsymFillHists.cxx.
Referenced by BookHists().
void MAsymFillHists::BookHistsByRing (ERingId ringId)
Definition at line 240 of file MAsymFillHists.cxx.
Referenced by BookHists().
void MAsymFillHists::Fill (const EventConfig & rc) [virtual]
Reimplemented from DrawObjContainer.
Definition at line 326 of file MAsymFillHists.cxx.
DrawObjContainer * MAsymFillHists::GetSingleFillHists (const AnaFillResult & afr)
Definition at line 702 of file MAsymFillHists.cxx.
Referenced by AnaFillResult::CalcAvrgAsymByBunch(), and PostFill().
void MAsymFillHists::PostFill () [virtual]
Reimplemented from DrawObjContainer.
Definition at line 425 of file MAsymFillHists.cxx.
void MAsymFillHists::PostFill (AnaGlobResult & agr) [virtual]
Reimplemented from DrawObjContainer.
Definition at line 521 of file MAsymFillHists.cxx.
void MAsymFillHists::UpdateLimits () [virtual]
Reimplemented from DrawObjContainer.
Definition at line 631 of file MAsymFillHists.cxx.
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/MAsymFillHists.h
/direct/eic+u/dsmirnov/cnipol/src/MAsymFillHists.cxx