cnipol: Calibrator Class Reference
Calibrator Class Reference
#include <Calibrator.h>
Public Member Functions
Calibrator ()
Default constructor.
~Calibrator ()
Default destructor.
virtual void UpdateMeanChannel ()
Calculates some statistical quantities (mean, chi^2/Ndf) for all valid channels in fChannelCalibs and saves them in fMeanChannel, a special dummy "channel" container.
ChannelCalib const & GetChannelCalib (uint16_t chId) const
ChannelCalib const & GetMeanChannel () const
ChannelCalib const & GetMeanOfLogsChannel () const
Float_t GetRMSBananaChi2Ndf () const
Float_t GetRMSOfLogsBananaChi2Ndf () const
virtual void CopyAlphaCoefs (Calibrator &other)
void UsePlainAlphaGain ()
void ApplyRun13BiasCurrentCorrection (MeasInfo *measInfo, bool direct)
virtual void Calibrate (DrawObjContainer *c)
Float_t GetEffectiveGain (UShort_t chId) const
virtual Float_t GetDLWidth (UShort_t chId) const
virtual Float_t GetDLWidthErr (UShort_t chId) const
virtual Float_t GetT0Coef (UShort_t chId) const
virtual Float_t GetT0CoefErr (UShort_t chId) const
virtual Float_t GetBananaChi2Ndf (UShort_t chId) const
virtual UInt_t GetFitStatus (UShort_t chId) const
virtual Float_t GetEnergyA (UShort_t adc, UShort_t chId) const
Returns energy registered by channel chId.
virtual Float_t GetKinEnergyA (UShort_t adc, UShort_t chId) const
virtual Float_t GetTime (UShort_t tdc) const
virtual Float_t GetTimeOfFlight (UShort_t tdc, UShort_t chId) const
virtual TFitResultPtr CalibrateOld (TH1 *h, TH1D *hMeanTime, UShort_t chId=0, Bool_t wideLimits=false)
virtual void Calibrate (TH1 *h, TH1D *hMeanTime, UShort_t chId=0, Bool_t wideLimits=false)
virtual void Print (const Option_t *opt="") const
virtual void PrintAsPhp (FILE *f=stdout) const
void PrintAsConfig (FILE *f=stdout) const
Protected Attributes
ChannelCalibMap fChannelCalibs
ChannelCalib fMeanChannel
A virtual "channel" to hold the mean values of all real channels.
ChannelCalib fMeanOfLogsChannel
Float_t fRMSBananaChi2Ndf
Float_t fRMSOfLogsBananaChi2Ndf
Detailed Description
Definition at line 21 of file Calibrator.h.
Constructor & Destructor Documentation
Calibrator::Calibrator ()
Default constructor.
Definition at line 19 of file Calibrator.cxx.
Calibrator::~Calibrator ()
Default destructor.
Definition at line 26 of file Calibrator.cxx.
Member Function Documentation
void Calibrator::ApplyRun13BiasCurrentCorrection (MeasInfo * measInfo, bool direct)
Definition at line 109 of file Calibrator.cxx.
Referenced by AsymRoot::Calibrate(), and AsymRoot::UpdateCalibrator().
void Calibrator::Calibrate (TH1 * h, TH1D * hMeanTime, UShort_t chId = 0, Bool_t wideLimits = false) [virtual]
Definition at line 310 of file Calibrator.cxx.
void Calibrator::Calibrate (DrawObjContainer * c) [virtual]
Reimplemented in AlphaCalibrator, DeadLayerCalibrator, and DeadLayerCalibratorEDepend.
Definition at line 206 of file Calibrator.cxx.
Referenced by AsymRoot::Calibrate().
TFitResultPtr Calibrator::CalibrateOld (TH1 * h, TH1D * hMeanTime, UShort_t chId = 0, Bool_t wideLimits = false) [virtual]
Reimplemented in DeadLayerCalibrator.
Definition at line 303 of file Calibrator.cxx.
void Calibrator::CopyAlphaCoefs (Calibrator & other) [virtual]
Definition at line 81 of file Calibrator.cxx.
Referenced by AsymRoot::UpdateCalibrator().
Float_t Calibrator::GetBananaChi2Ndf (UShort_t chId) const [virtual]
Definition at line 241 of file Calibrator.cxx.
Referenced by CnipolCalibHists::PostFill().
ChannelCalib const& Calibrator::GetChannelCalib (uint16_t chId) const [inline]
Definition at line 29 of file Calibrator.h.
Referenced by MAsymRunHists::Fill(), MAsymRateHists::Fill(), ChannelEvent::GetEnergyI(), ChannelEvent::GetKinEnergyA(), ChannelEvent::GetKinEnergyADLCorrEstimate(), ChannelEvent::GetKinEnergyAEDepend(), ChannelEvent::GetKinEnergyAEDependAverage(), ChannelEvent::GetKinEnergyAEstimate(), ChannelEvent::GetKinEnergyAEstimateEDepend(), ChannelEvent::GetTimeOfFlight(), ChannelEvent::GetTimeOfFlight2(), and ChannelEvent::GetTimeOfFlightEstimate().
Float_t Calibrator::GetDLWidth (UShort_t chId) const [virtual]
Definition at line 220 of file Calibrator.cxx.
Referenced by CnipolCalibHists::PostFill().
Float_t Calibrator::GetDLWidthErr (UShort_t chId) const [virtual]
Definition at line 227 of file Calibrator.cxx.
Referenced by CnipolCalibHists::PostFill().
Float_t Calibrator::GetEffectiveGain (UShort_t chId) const
Definition at line 213 of file Calibrator.cxx.
Float_t Calibrator::GetEnergyA (UShort_t adc, UShort_t chId) const [virtual]
Returns energy registered by channel chId.
Definition at line 268 of file Calibrator.cxx.
Referenced by CnipolHists::ConvertRawToKin(), ChannelEvent::GetEnergyA(), and GetKinEnergyA().
UInt_t Calibrator::GetFitStatus (UShort_t chId) const [virtual]
Definition at line 248 of file Calibrator.cxx.
Referenced by AsymCalculator::CalcChannelAsym(), AsymCalculator::CalcStripAsymmetry(), and CnipolCalibHists::PostFill().
Float_t Calibrator::GetKinEnergyA (UShort_t adc, UShort_t chId) const [virtual]
Definition at line 279 of file Calibrator.cxx.
ChannelCalib const& Calibrator::GetMeanChannel () const [inline]
Definition at line 30 of file Calibrator.h.
Referenced by MAsymRunHists::Fill(), and CnipolCalibHists::PostFill().
ChannelCalib const& Calibrator::GetMeanOfLogsChannel () const [inline]
Definition at line 31 of file Calibrator.h.
Referenced by CnipolCalibHists::PostFill().
Float_t Calibrator::GetRMSBananaChi2Ndf () const [inline]
Definition at line 32 of file Calibrator.h.
Float_t Calibrator::GetRMSOfLogsBananaChi2Ndf () const [inline]
Definition at line 33 of file Calibrator.h.
Referenced by CnipolCalibHists::PostFill().
Float_t Calibrator::GetT0Coef (UShort_t chId) const [virtual]
Definition at line 234 of file Calibrator.cxx.
Referenced by CnipolCalibHists::PostFill().
Float_t Calibrator::GetT0CoefErr (UShort_t chId) const [virtual]
Definition at line 261 of file Calibrator.cxx.
Referenced by CnipolCalibHists::PostFill().
Float_t Calibrator::GetTime (UShort_t tdc) const [virtual]
Definition at line 288 of file Calibrator.cxx.
Referenced by GetTimeOfFlight().
Float_t Calibrator::GetTimeOfFlight (UShort_t tdc, UShort_t chId) const [virtual]
Definition at line 295 of file Calibrator.cxx.
Referenced by CnipolHists::ConvertRawToKin().
void Calibrator::Print (const Option_t * opt = "") const [virtual]
Definition at line 316 of file Calibrator.cxx.
void Calibrator::PrintAsConfig (FILE * f = stdout) const
Definition at line 354 of file Calibrator.cxx.
Referenced by EventConfig::PrintAsConfig().
void Calibrator::PrintAsPhp (FILE * f = stdout) const [virtual]
Definition at line 336 of file Calibrator.cxx.
Referenced by EventConfig::PrintAsPhp().
void Calibrator::UpdateMeanChannel () [virtual]
Calculates some statistical quantities (mean, chi^2/Ndf) for all valid channels in fChannelCalibs and saves them in fMeanChannel, a special dummy "channel" container.
Definition at line 36 of file Calibrator.cxx.
Referenced by DeadLayerCalibratorEDepend::Calibrate().
void Calibrator::UsePlainAlphaGain ()
Definition at line 97 of file Calibrator.cxx.
Referenced by ApplyRun13BiasCurrentCorrection(), and AsymRoot::UpdateCalibrator().
Member Data Documentation
ChannelCalibMap Calibrator::fChannelCalibs [protected]
Definition at line 57 of file Calibrator.h.
Referenced by ApplyRun13BiasCurrentCorrection(), AlphaCalibrator::Calibrate(), AlphaCalibrator::CalibrateBadChannels(), DeadLayerCalibrator::CalibrateOld(), CopyAlphaCoefs(), GetBananaChi2Ndf(), GetChannelCalib(), GetDLWidth(), GetDLWidthErr(), GetEffectiveGain(), GetEnergyA(), GetFitStatus(), GetKinEnergyA(), GetT0Coef(), GetT0CoefErr(), GetTimeOfFlight(), Print(), PrintAsConfig(), PrintAsPhp(), UpdateMeanChannel(), and UsePlainAlphaGain().
ChannelCalib Calibrator::fMeanChannel [protected]
A virtual "channel" to hold the mean values of all real channels.
Definition at line 58 of file Calibrator.h.
Referenced by GetMeanChannel(), and UpdateMeanChannel().
ChannelCalib Calibrator::fMeanOfLogsChannel [protected]
Definition at line 59 of file Calibrator.h.
Referenced by GetMeanOfLogsChannel(), and UpdateMeanChannel().
Float_t Calibrator::fRMSBananaChi2Ndf [protected]
Definition at line 60 of file Calibrator.h.
Referenced by GetRMSBananaChi2Ndf(), and UpdateMeanChannel().
Float_t Calibrator::fRMSOfLogsBananaChi2Ndf [protected]
Definition at line 61 of file Calibrator.h.
Referenced by GetRMSOfLogsBananaChi2Ndf(), and UpdateMeanChannel().
The documentation for this class was generated from the following files:
/direct/eic+u/dsmirnov/cnipol/inc/Calibrator.h
/direct/eic+u/dsmirnov/cnipol/src/Calibrator.cxx