cnipol: inc/MseRunPeriod.h File Reference
MseRunPeriod.h File Reference
#include <stdio.h>
#include "mysql++.h"
#include "ssqls.h"
#include "TObject.h"
Macros
#define MYSQLPP_SSQLS_NO_STATICS
#define MseRunPeriod_h
Functions
sql_create_17(MseRunPeriod,
1, 2, mysqlpp::sql_datetime,
start_time,
mysqlpp::sql_smallint,
polarimeter_id,
mysqlpp::sql_varchar,
alpha_calib_run_name,
mysqlpp::sql_tinyint_unsigned,
alpha_source_count,
mysqlpp::sql_varchar,
disabled_channels,
mysqlpp::sql_varchar,
disabled_bunches,
mysqlpp::sql_float,
cut_proto_slope,
mysqlpp::sql_float,
cut_proto_offset,
mysqlpp::sql_tinyint_unsigned,
cut_proto_width,
mysqlpp::sql_float,
cut_proto_adc_min,
mysqlpp::sql_float,
cut_proto_adc_max,
mysqlpp::sql_float,
cut_proto_tdc_min,
mysqlpp::sql_float,
cut_proto_tdc_max,
mysqlpp::sql_float,
cut_pulser_adc_min,
mysqlpp::sql_float,
cut_pulser_adc_max,
mysqlpp::sql_float,
cut_pulser_tdc_min,
mysqlpp::sql_float,
cut_pulser_tdc_max) class
MseRunPeriodX MseRunPeriodX (const mysqlpp::sql_datetime &p1)
MseRunPeriodX (const mysqlpp::sql_datetime &p1, const mysqlpp::sql_smallint &p2)
MseRunPeriodX (const mysqlpp::Row &row)
void Init ()
void Print (const Option_t *opt="") const
void PrintAsPhp (FILE *f=stdout) const
Macro Definition Documentation
#define MseRunPeriod_h
Definition at line 6 of file MseRunPeriod.h.
#define MYSQLPP_SSQLS_NO_STATICS
Definition at line 2 of file MseRunPeriod.h.
Function Documentation
void Init ()
MseRunPeriodX::MseRunPeriodX (const mysqlpp::sql_datetime & p1)
Definition at line 17 of file MseRunPeriod.cxx.
Referenced by AsymDbSql::CompleteMeasInfoByRunPeriod(), main(), and AsymDbSql::SelectRunPeriod().
MseRunPeriodX (const mysqlpp::sql_datetime & p1, const mysqlpp::sql_smallint & p2)
Definition at line 45 of file MseRunPeriod.h.
MseRunPeriodX (const mysqlpp::Row & row)
Definition at line 50 of file MseRunPeriod.h.
void Print (const Option_t * opt = "") const
void PrintAsPhp (FILE * f = stdout) const