cnipol: /direct/eic+u/dsmirnov/cnipol/inc/RawDataReader.h File Reference
RawDataReader.h File Reference
#include <errno.h>
#include <fstream>
#include <iostream>
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "rhicpol.h"
#include "rpoldata.h"
#include "AsymGlobals.h"
#include "MeasInfo.h"
#include "MseMeasInfo.h"
Classes
class RawDataReader
This class loads a raw data file into memory, processes data structures with information about the measurement, and loops over the events.
Functions
void UpdateRunConst (TRecordConfigRhicStruct *ci)
void DecodeTargetID (const polDataStruct &poldat, MseMeasInfoX &run)
Decorde target infomation.
void ProcessRecordPCTarget (const pCTargetStruct &rec, MseMeasInfoX &run)
void ProcessRecord (const recordConfigRhicStruct &rec)
void ProcessRecord (const recordMeasTypeStruct &rec)
void ProcessRecord (const recordPolAdoStruct &rec, MseMeasInfoX &MeasInfo)
void ProcessRecord (const recordpCTagAdoStruct &rec, MseMeasInfoX &run)
void ProcessRecord (const recordWFDV8ArrayStruct &rec)
void ProcessRecord (const recordCountRate &rec)
void ProcessRecord (const recordWcmAdoStruct &rec)
void ProcessRecord (const RecordWcm &rec)
void ProcessRecord (const recordBeamAdoStruct &rec)
void ProcessRecord (const RecordMachineParams &rec)
void ProcessRecord (const RecordTargetParams &rec)
Function Documentation
void DecodeTargetID (const polDataStruct & poldat, MseMeasInfoX & mseMeasInfo)
Decorde target infomation.
Presently the target ID is assumed to be appear at the last of character string poldat.targetIdS
Definition at line 465 of file RawDataReader.cxx.
Referenced by ProcessRecord().
void ProcessRecord (const RecordTargetParams & rec)
Definition at line 906 of file RawDataReader.cxx.
void ProcessRecord (const RecordMachineParams & rec)
Definition at line 899 of file RawDataReader.cxx.
void ProcessRecord (const recordBeamAdoStruct & rec)
Definition at line 946 of file RawDataReader.cxx.
void ProcessRecord (const RecordWcm & rec)
Definition at line 933 of file RawDataReader.cxx.
void ProcessRecord (const recordWcmAdoStruct & rec)
Definition at line 913 of file RawDataReader.cxx.
void ProcessRecord (const recordCountRate & rec)
Definition at line 887 of file RawDataReader.cxx.
void ProcessRecord (const recordWFDV8ArrayStruct & rec)
Definition at line 850 of file RawDataReader.cxx.
void ProcessRecord (const recordpCTagAdoStruct & rec, MseMeasInfoX & run)
Definition at line 839 of file RawDataReader.cxx.
void ProcessRecord (const recordPolAdoStruct & rec, MseMeasInfoX & MeasInfo)
Definition at line 832 of file RawDataReader.cxx.
void ProcessRecord (const recordMeasTypeStruct & rec)
Definition at line 825 of file RawDataReader.cxx.
void ProcessRecord (const recordConfigRhicStruct & rec)
Definition at line 812 of file RawDataReader.cxx.
Referenced by RawDataReader::ReadMeasInfo().
void ProcessRecordPCTarget (const pCTargetStruct & rec, MseMeasInfoX & run)
void UpdateRunConst (TRecordConfigRhicStruct * ci)
Definition at line 418 of file RawDataReader.cxx.
Referenced by ProcessRecord().