cnipol: /direct/eic+u/dsmirnov/cnipol/src/spinflipper.cxx File Reference
spinflipper.cxx File Reference
#include <fstream>
#include <sstream>
#include <string>
#include "TGraphErrors.h"
#include "TFile.h"
#include "EventConfig.h"
#include "DrawObjContainer.h"
#include "CnipolSpinStudyHists.h"
#include "TCanvas.h"
#include "TROOT.h"
#include "utils/utils.h"
Functions
void changePhase (TGraphErrors *gr, Double_t phase)
void removePoints (TGraphErrors *gr)
double calcSpinFlipperPhase (uint markerAbsRev, uint markerRelRev, uint spinFlipperTune)
int main (int argc, char *argv[])
Function Documentation
double calcSpinFlipperPhase (uint markerAbsRev, uint markerRelRev, uint spinFlipperTune)
Definition at line 184 of file spinflipper.cxx.
Referenced by main().
void changePhase (TGraphErrors * gr, Double_t phase)
Definition at line 158 of file spinflipper.cxx.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 27 of file spinflipper.cxx.
void removePoints (TGraphErrors * gr)
Definition at line 174 of file spinflipper.cxx.
Referenced by main().